#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimNotify_PlayParticleDIH

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function AnimNotify_PlayParticleDIH.AnimNotify_PlayParticleDIH_C.Received_Notify
// 0x0100 (0x0100 - 0x0000)
struct AnimNotify_PlayParticleDIH_C_Received_Notify final
{
public:
	class USkeletalMeshComponent*                 MeshComp;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimSequenceBase*                      Animation;                                         // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0xF];                                       // 0x0011(0x000F)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             LocalTransform;                                    // 0x0020(0x0030)(Edit, BlueprintVisible, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51[0x3];                                       // 0x0051(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_BreakTransform_Location;                  // 0x0054(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation;                  // 0x0060(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale;                     // 0x006C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_ComposeRotators_ReturnValue;              // 0x0078(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_TransformLocation_ReturnValue;            // 0x0084(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             CallFunc_GetSocketTransform_ReturnValue;           // 0x0090(0x0030)(IsPlainOldData, NoDestructor)
	class FString                                 CallFunc_GetCurrentLevelName_ReturnValue;          // 0x00C0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Conv_StringToName_ReturnValue;            // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystem*                        CallFunc_Map_Find_Value;                           // 0x00D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E1[0x7];                                       // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystem*                        K2Node_Select_Default;                             // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAttached_ReturnValue;         // 0x00F0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue;       // 0x00F8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AnimNotify_PlayParticleDIH_C_Received_Notify) == 0x000010, "Wrong alignment on AnimNotify_PlayParticleDIH_C_Received_Notify");
static_assert(sizeof(AnimNotify_PlayParticleDIH_C_Received_Notify) == 0x000100, "Wrong size on AnimNotify_PlayParticleDIH_C_Received_Notify");
static_assert(offsetof(AnimNotify_PlayParticleDIH_C_Received_Notify, MeshComp) == 0x000000, "Member 'AnimNotify_PlayParticleDIH_C_Received_Notify::MeshComp' has a wrong offset!");
static_assert(offsetof(AnimNotify_PlayParticleDIH_C_Received_Notify, Animation) == 0x000008, "Member 'AnimNotify_PlayParticleDIH_C_Received_Notify::Animation' has a wrong offset!");
static_assert(offsetof(AnimNotify_PlayParticleDIH_C_Received_Notify, ReturnValue) == 0x000010, "Member 'AnimNotify_PlayParticleDIH_C_Received_Notify::ReturnValue' has a wrong offset!");
static_assert(offsetof(AnimNotify_PlayParticleDIH_C_Received_Notify, LocalTransform) == 0x000020, "Member 'AnimNotify_PlayParticleDIH_C_Received_Notify::LocalTransform' has a wrong offset!");
static_assert(offsetof(AnimNotify_PlayParticleDIH_C_Received_Notify, Temp_bool_Variable) == 0x000050, "Member 'AnimNotify_PlayParticleDIH_C_Received_Notify::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(AnimNotify_PlayParticleDIH_C_Received_Notify, CallFunc_BreakTransform_Location) == 0x000054, "Member 'AnimNotify_PlayParticleDIH_C_Received_Notify::CallFunc_BreakTransform_Location' has a wrong offset!");
static_assert(offsetof(AnimNotify_PlayParticleDIH_C_Received_Notify, CallFunc_BreakTransform_Rotation) == 0x000060, "Member 'AnimNotify_PlayParticleDIH_C_Received_Notify::CallFunc_BreakTransform_Rotation' has a wrong offset!");
static_assert(offsetof(AnimNotify_PlayParticleDIH_C_Received_Notify, CallFunc_BreakTransform_Scale) == 0x00006C, "Member 'AnimNotify_PlayParticleDIH_C_Received_Notify::CallFunc_BreakTransform_Scale' has a wrong offset!");
static_assert(offsetof(AnimNotify_PlayParticleDIH_C_Received_Notify, CallFunc_ComposeRotators_ReturnValue) == 0x000078, "Member 'AnimNotify_PlayParticleDIH_C_Received_Notify::CallFunc_ComposeRotators_ReturnValue' has a wrong offset!");
static_assert(offsetof(AnimNotify_PlayParticleDIH_C_Received_Notify, CallFunc_TransformLocation_ReturnValue) == 0x000084, "Member 'AnimNotify_PlayParticleDIH_C_Received_Notify::CallFunc_TransformLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(AnimNotify_PlayParticleDIH_C_Received_Notify, CallFunc_GetSocketTransform_ReturnValue) == 0x000090, "Member 'AnimNotify_PlayParticleDIH_C_Received_Notify::CallFunc_GetSocketTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(AnimNotify_PlayParticleDIH_C_Received_Notify, CallFunc_GetCurrentLevelName_ReturnValue) == 0x0000C0, "Member 'AnimNotify_PlayParticleDIH_C_Received_Notify::CallFunc_GetCurrentLevelName_ReturnValue' has a wrong offset!");
static_assert(offsetof(AnimNotify_PlayParticleDIH_C_Received_Notify, CallFunc_Conv_StringToName_ReturnValue) == 0x0000D0, "Member 'AnimNotify_PlayParticleDIH_C_Received_Notify::CallFunc_Conv_StringToName_ReturnValue' has a wrong offset!");
static_assert(offsetof(AnimNotify_PlayParticleDIH_C_Received_Notify, CallFunc_Map_Find_Value) == 0x0000D8, "Member 'AnimNotify_PlayParticleDIH_C_Received_Notify::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(AnimNotify_PlayParticleDIH_C_Received_Notify, CallFunc_Map_Find_ReturnValue) == 0x0000E0, "Member 'AnimNotify_PlayParticleDIH_C_Received_Notify::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(AnimNotify_PlayParticleDIH_C_Received_Notify, K2Node_Select_Default) == 0x0000E8, "Member 'AnimNotify_PlayParticleDIH_C_Received_Notify::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(AnimNotify_PlayParticleDIH_C_Received_Notify, CallFunc_SpawnEmitterAttached_ReturnValue) == 0x0000F0, "Member 'AnimNotify_PlayParticleDIH_C_Received_Notify::CallFunc_SpawnEmitterAttached_ReturnValue' has a wrong offset!");
static_assert(offsetof(AnimNotify_PlayParticleDIH_C_Received_Notify, CallFunc_SpawnEmitterAtLocation_ReturnValue) == 0x0000F8, "Member 'AnimNotify_PlayParticleDIH_C_Received_Notify::CallFunc_SpawnEmitterAtLocation_ReturnValue' has a wrong offset!");

// Function AnimNotify_PlayParticleDIH.AnimNotify_PlayParticleDIH_C.GetNotifyName
// 0x0020 (0x0020 - 0x0000)
struct AnimNotify_PlayParticleDIH_C_GetNotifyName final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)
	class FString                                 CallFunc_GetDisplayName_ReturnValue;               // 0x0010(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(AnimNotify_PlayParticleDIH_C_GetNotifyName) == 0x000008, "Wrong alignment on AnimNotify_PlayParticleDIH_C_GetNotifyName");
static_assert(sizeof(AnimNotify_PlayParticleDIH_C_GetNotifyName) == 0x000020, "Wrong size on AnimNotify_PlayParticleDIH_C_GetNotifyName");
static_assert(offsetof(AnimNotify_PlayParticleDIH_C_GetNotifyName, ReturnValue) == 0x000000, "Member 'AnimNotify_PlayParticleDIH_C_GetNotifyName::ReturnValue' has a wrong offset!");
static_assert(offsetof(AnimNotify_PlayParticleDIH_C_GetNotifyName, CallFunc_GetDisplayName_ReturnValue) == 0x000010, "Member 'AnimNotify_PlayParticleDIH_C_GetNotifyName::CallFunc_GetDisplayName_ReturnValue' has a wrong offset!");

}

