#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Bats

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Bats.BP_Bats_C
// 0x0078 (0x0298 - 0x0220)
class ABP_Bats_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient, UObjectWrapper)
	class UProjectileMovementComponent*           ProjectileMovement;                                // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPointLightComponent*                   PointLight;                                        // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               P_BatsFollow;                                      // 0x0238(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Bat7;                                              // 0x0240(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Bat6;                                              // 0x0248(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Bat1;                                              // 0x0250(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Bat4;                                              // 0x0258(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Bat3;                                              // 0x0260(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Bat2;                                              // 0x0268(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 Bat5;                                              // 0x0270(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UArrowComponent*                        Arrow;                                             // 0x0278(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0280(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Duration;                                          // 0x0288(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                TargetLocation;                                    // 0x028C(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Bats(int32 EntryPoint);
	void ReceiveBeginPlay();
	void InitialiseBats(const struct FVector& Start, const struct FVector& End);
	void RotateBats(class USceneComponent* BatComponent, float AngleDeg);
	void ReceiveTick(float DeltaSeconds);
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Bats_C">();
	}
	static class ABP_Bats_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Bats_C>();
	}
};
static_assert(alignof(ABP_Bats_C) == 0x000008, "Wrong alignment on ABP_Bats_C");
static_assert(sizeof(ABP_Bats_C) == 0x000298, "Wrong size on ABP_Bats_C");
static_assert(offsetof(ABP_Bats_C, UberGraphFrame) == 0x000220, "Member 'ABP_Bats_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_Bats_C, ProjectileMovement) == 0x000228, "Member 'ABP_Bats_C::ProjectileMovement' has a wrong offset!");
static_assert(offsetof(ABP_Bats_C, PointLight) == 0x000230, "Member 'ABP_Bats_C::PointLight' has a wrong offset!");
static_assert(offsetof(ABP_Bats_C, P_BatsFollow) == 0x000238, "Member 'ABP_Bats_C::P_BatsFollow' has a wrong offset!");
static_assert(offsetof(ABP_Bats_C, Bat7) == 0x000240, "Member 'ABP_Bats_C::Bat7' has a wrong offset!");
static_assert(offsetof(ABP_Bats_C, Bat6) == 0x000248, "Member 'ABP_Bats_C::Bat6' has a wrong offset!");
static_assert(offsetof(ABP_Bats_C, Bat1) == 0x000250, "Member 'ABP_Bats_C::Bat1' has a wrong offset!");
static_assert(offsetof(ABP_Bats_C, Bat4) == 0x000258, "Member 'ABP_Bats_C::Bat4' has a wrong offset!");
static_assert(offsetof(ABP_Bats_C, Bat3) == 0x000260, "Member 'ABP_Bats_C::Bat3' has a wrong offset!");
static_assert(offsetof(ABP_Bats_C, Bat2) == 0x000268, "Member 'ABP_Bats_C::Bat2' has a wrong offset!");
static_assert(offsetof(ABP_Bats_C, Bat5) == 0x000270, "Member 'ABP_Bats_C::Bat5' has a wrong offset!");
static_assert(offsetof(ABP_Bats_C, Arrow) == 0x000278, "Member 'ABP_Bats_C::Arrow' has a wrong offset!");
static_assert(offsetof(ABP_Bats_C, DefaultSceneRoot) == 0x000280, "Member 'ABP_Bats_C::DefaultSceneRoot' has a wrong offset!");
static_assert(offsetof(ABP_Bats_C, Duration) == 0x000288, "Member 'ABP_Bats_C::Duration' has a wrong offset!");
static_assert(offsetof(ABP_Bats_C, TargetLocation) == 0x00028C, "Member 'ABP_Bats_C::TargetLocation' has a wrong offset!");

}

