#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BreadcrumbButton

#include "Basic.hpp"

#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function BP_BreadcrumbButton.BP_BreadcrumbButton_C.ExecuteUbergraph_BP_BreadcrumbButton
// 0x0004 (0x0004 - 0x0000)
struct BP_BreadcrumbButton_C_ExecuteUbergraph_BP_BreadcrumbButton final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_BreadcrumbButton_C_ExecuteUbergraph_BP_BreadcrumbButton) == 0x000004, "Wrong alignment on BP_BreadcrumbButton_C_ExecuteUbergraph_BP_BreadcrumbButton");
static_assert(sizeof(BP_BreadcrumbButton_C_ExecuteUbergraph_BP_BreadcrumbButton) == 0x000004, "Wrong size on BP_BreadcrumbButton_C_ExecuteUbergraph_BP_BreadcrumbButton");
static_assert(offsetof(BP_BreadcrumbButton_C_ExecuteUbergraph_BP_BreadcrumbButton, EntryPoint) == 0x000000, "Member 'BP_BreadcrumbButton_C_ExecuteUbergraph_BP_BreadcrumbButton::EntryPoint' has a wrong offset!");

// Function BP_BreadcrumbButton.BP_BreadcrumbButton_C.Update
// 0x0078 (0x0078 - 0x0000)
struct BP_BreadcrumbButton_C_Update final
{
public:
	class FText                                   Text_0;                                            // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FString                                 Breadcrumb_0;                                      // 0x0018(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0030(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x0048(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0058(0x0018)()
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_TextIsEmpty_ReturnValue;                  // 0x0071(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0072(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_BreadcrumbButton_C_Update) == 0x000008, "Wrong alignment on BP_BreadcrumbButton_C_Update");
static_assert(sizeof(BP_BreadcrumbButton_C_Update) == 0x000078, "Wrong size on BP_BreadcrumbButton_C_Update");
static_assert(offsetof(BP_BreadcrumbButton_C_Update, Text_0) == 0x000000, "Member 'BP_BreadcrumbButton_C_Update::Text_0' has a wrong offset!");
static_assert(offsetof(BP_BreadcrumbButton_C_Update, Breadcrumb_0) == 0x000018, "Member 'BP_BreadcrumbButton_C_Update::Breadcrumb_0' has a wrong offset!");
static_assert(offsetof(BP_BreadcrumbButton_C_Update, Temp_bool_Variable) == 0x000028, "Member 'BP_BreadcrumbButton_C_Update::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BP_BreadcrumbButton_C_Update, CallFunc_Conv_TextToString_ReturnValue) == 0x000030, "Member 'BP_BreadcrumbButton_C_Update::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BreadcrumbButton_C_Update, Temp_byte_Variable) == 0x000040, "Member 'BP_BreadcrumbButton_C_Update::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(BP_BreadcrumbButton_C_Update, CallFunc_Concat_StrStr_ReturnValue) == 0x000048, "Member 'BP_BreadcrumbButton_C_Update::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BreadcrumbButton_C_Update, CallFunc_Conv_StringToText_ReturnValue) == 0x000058, "Member 'BP_BreadcrumbButton_C_Update::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BreadcrumbButton_C_Update, Temp_byte_Variable_1) == 0x000070, "Member 'BP_BreadcrumbButton_C_Update::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_BreadcrumbButton_C_Update, CallFunc_TextIsEmpty_ReturnValue) == 0x000071, "Member 'BP_BreadcrumbButton_C_Update::CallFunc_TextIsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BreadcrumbButton_C_Update, K2Node_Select_Default) == 0x000072, "Member 'BP_BreadcrumbButton_C_Update::K2Node_Select_Default' has a wrong offset!");

}

