#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BlessingAttachPolehammer

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_BlessingAttachPolehammer.BP_BlessingAttachPolehammer_C.ExecuteUbergraph_BP_BlessingAttachPolehammer
// 0x01C0 (0x01C0 - 0x0000)
struct BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0004(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OverlappedComponent;    // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_ComponentBoundEvent_OtherActor;             // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_ComponentBoundEvent_OtherComp;              // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_OtherBodyIndex;         // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bFromSweep;             // 0x002C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_ComponentBoundEvent_SweepResult;            // 0x0030(0x008C)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	uint8                                         Pad_BC[0x4];                                       // 0x00BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_DemonHordeEnemy_C*                  K2Node_DynamicCast_AsBP_Demon_Horde_Enemy;         // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Trip_ReturnValue;                         // 0x00C9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x00CA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00CB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x00CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x00CD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x00CE(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetIsDead_ReturnValue;                    // 0x00CF(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x00D0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_MakeHitResult_ReturnValue;                // 0x00DC(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0168(0x0010)(ZeroConstructor, NoDestructor)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0178(0x0008)(NoDestructor, HasGetValueTypeHash)
	class AController*                            CallFunc_GetControllerIncludingVehicle_ReturnValue; // 0x0180(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_MordhauTakeDamage_ReturnValue;            // 0x0188(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetDirectionUnitVector_ReturnValue;       // 0x018C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue;         // 0x0198(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_X;                            // 0x01A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Y;                            // 0x01A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Z;                            // 0x01AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x01B0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer) == 0x000008, "Wrong alignment on BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer");
static_assert(sizeof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer) == 0x0001C0, "Wrong size on BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, EntryPoint) == 0x000000, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000004, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, K2Node_ComponentBoundEvent_OverlappedComponent) == 0x000010, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::K2Node_ComponentBoundEvent_OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, K2Node_ComponentBoundEvent_OtherActor) == 0x000018, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::K2Node_ComponentBoundEvent_OtherActor' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, K2Node_ComponentBoundEvent_OtherComp) == 0x000020, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::K2Node_ComponentBoundEvent_OtherComp' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, K2Node_ComponentBoundEvent_OtherBodyIndex) == 0x000028, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::K2Node_ComponentBoundEvent_OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, K2Node_ComponentBoundEvent_bFromSweep) == 0x00002C, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::K2Node_ComponentBoundEvent_bFromSweep' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, K2Node_ComponentBoundEvent_SweepResult) == 0x000030, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::K2Node_ComponentBoundEvent_SweepResult' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, K2Node_DynamicCast_AsBP_Demon_Horde_Enemy) == 0x0000C0, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::K2Node_DynamicCast_AsBP_Demon_Horde_Enemy' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, K2Node_DynamicCast_bSuccess) == 0x0000C8, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, CallFunc_Trip_ReturnValue) == 0x0000C9, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::CallFunc_Trip_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x0000CA, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, CallFunc_IsValid_ReturnValue) == 0x0000CB, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, CallFunc_HasAuthority_ReturnValue) == 0x0000CC, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, CallFunc_IsValid_ReturnValue_1) == 0x0000CD, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, CallFunc_IsValid_ReturnValue_2) == 0x0000CE, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, CallFunc_GetIsDead_ReturnValue) == 0x0000CF, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::CallFunc_GetIsDead_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x0000D0, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, CallFunc_MakeHitResult_ReturnValue) == 0x0000DC, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::CallFunc_MakeHitResult_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, K2Node_CreateDelegate_OutputDelegate) == 0x000168, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000178, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, CallFunc_GetControllerIncludingVehicle_ReturnValue) == 0x000180, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::CallFunc_GetControllerIncludingVehicle_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, CallFunc_MordhauTakeDamage_ReturnValue) == 0x000188, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::CallFunc_MordhauTakeDamage_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, CallFunc_GetDirectionUnitVector_ReturnValue) == 0x00018C, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::CallFunc_GetDirectionUnitVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, CallFunc_Multiply_VectorFloat_ReturnValue) == 0x000198, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::CallFunc_Multiply_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, CallFunc_BreakVector_X) == 0x0001A4, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, CallFunc_BreakVector_Y) == 0x0001A8, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, CallFunc_BreakVector_Z) == 0x0001AC, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer, CallFunc_MakeVector_ReturnValue) == 0x0001B0, "Member 'BP_BlessingAttachPolehammer_C_ExecuteUbergraph_BP_BlessingAttachPolehammer::CallFunc_MakeVector_ReturnValue' has a wrong offset!");

// Function BP_BlessingAttachPolehammer.BP_BlessingAttachPolehammer_C.BndEvt__BP_BlessingAttachPolehammer_Capsule_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature
// 0x00B0 (0x00B0 - 0x0000)
struct BP_BlessingAttachPolehammer_C_BndEvt__BP_BlessingAttachPolehammer_Capsule_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature final
{
public:
	class UPrimitiveComponent*                    OverlappedComponent;                               // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         OtherBodyIndex;                                    // 0x0018(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bFromSweep;                                        // 0x001C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             SweepResult;                                       // 0x0020(0x008C)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(BP_BlessingAttachPolehammer_C_BndEvt__BP_BlessingAttachPolehammer_Capsule_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature) == 0x000008, "Wrong alignment on BP_BlessingAttachPolehammer_C_BndEvt__BP_BlessingAttachPolehammer_Capsule_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(sizeof(BP_BlessingAttachPolehammer_C_BndEvt__BP_BlessingAttachPolehammer_Capsule_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature) == 0x0000B0, "Wrong size on BP_BlessingAttachPolehammer_C_BndEvt__BP_BlessingAttachPolehammer_Capsule_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_BndEvt__BP_BlessingAttachPolehammer_Capsule_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, OverlappedComponent) == 0x000000, "Member 'BP_BlessingAttachPolehammer_C_BndEvt__BP_BlessingAttachPolehammer_Capsule_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::OverlappedComponent' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_BndEvt__BP_BlessingAttachPolehammer_Capsule_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, OtherActor) == 0x000008, "Member 'BP_BlessingAttachPolehammer_C_BndEvt__BP_BlessingAttachPolehammer_Capsule_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::OtherActor' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_BndEvt__BP_BlessingAttachPolehammer_Capsule_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, OtherComp) == 0x000010, "Member 'BP_BlessingAttachPolehammer_C_BndEvt__BP_BlessingAttachPolehammer_Capsule_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::OtherComp' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_BndEvt__BP_BlessingAttachPolehammer_Capsule_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, OtherBodyIndex) == 0x000018, "Member 'BP_BlessingAttachPolehammer_C_BndEvt__BP_BlessingAttachPolehammer_Capsule_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::OtherBodyIndex' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_BndEvt__BP_BlessingAttachPolehammer_Capsule_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, bFromSweep) == 0x00001C, "Member 'BP_BlessingAttachPolehammer_C_BndEvt__BP_BlessingAttachPolehammer_Capsule_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::bFromSweep' has a wrong offset!");
static_assert(offsetof(BP_BlessingAttachPolehammer_C_BndEvt__BP_BlessingAttachPolehammer_Capsule_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature, SweepResult) == 0x000020, "Member 'BP_BlessingAttachPolehammer_C_BndEvt__BP_BlessingAttachPolehammer_Capsule_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature::SweepResult' has a wrong offset!");

}

