#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BloatedCarcassFists

#include "Basic.hpp"

#include "BP_FistsWeapon_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BloatedCarcassFists.BP_BloatedCarcassFists_C
// 0x0000 (0x1C90 - 0x1C90)
class ABP_BloatedCarcassFists_C final : public ABP_FistsWeapon_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BloatedCarcassFists_C">();
	}
	static class ABP_BloatedCarcassFists_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BloatedCarcassFists_C>();
	}
};
static_assert(alignof(ABP_BloatedCarcassFists_C) == 0x000010, "Wrong alignment on ABP_BloatedCarcassFists_C");
static_assert(sizeof(ABP_BloatedCarcassFists_C) == 0x001C90, "Wrong size on ABP_BloatedCarcassFists_C");

}

