#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BlessingProjectile_Coin

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_RockProjectile_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BlessingProjectile_Coin.BP_BlessingProjectile_Coin_C
// 0x0010 (0x0870 - 0x0860)
class ABP_BlessingProjectile_Coin_C final : public ABP_RockProjectile_C
{
public:
	uint8                                         Pad_854[0x4];                                      // 0x0854(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_BlessingProjectile_Coin_C;       // 0x0858(0x0008)(ZeroConstructor, Transient, DuplicateTransient, UObjectWrapper)
	class UStaticMeshComponent*                   coin_01;                                           // 0x0860(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class AController*                            Controller;                                        // 0x0868(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_BlessingProjectile_Coin(int32 EntryPoint);
	void OnProjectileDamagedDamagable(class UDamageableComponent* DamagableComp, bool bWillKill, const struct FVector& WorldLocation, class FName bone);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BlessingProjectile_Coin_C">();
	}
	static class ABP_BlessingProjectile_Coin_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BlessingProjectile_Coin_C>();
	}
};
static_assert(alignof(ABP_BlessingProjectile_Coin_C) == 0x000010, "Wrong alignment on ABP_BlessingProjectile_Coin_C");
static_assert(sizeof(ABP_BlessingProjectile_Coin_C) == 0x000870, "Wrong size on ABP_BlessingProjectile_Coin_C");
static_assert(offsetof(ABP_BlessingProjectile_Coin_C, UberGraphFrame_BP_BlessingProjectile_Coin_C) == 0x000858, "Member 'ABP_BlessingProjectile_Coin_C::UberGraphFrame_BP_BlessingProjectile_Coin_C' has a wrong offset!");
static_assert(offsetof(ABP_BlessingProjectile_Coin_C, coin_01) == 0x000860, "Member 'ABP_BlessingProjectile_Coin_C::coin_01' has a wrong offset!");
static_assert(offsetof(ABP_BlessingProjectile_Coin_C, Controller) == 0x000868, "Member 'ABP_BlessingProjectile_Coin_C::Controller' has a wrong offset!");

}

