#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BattleRoyaleGameModeMetadata

#include "Basic.hpp"

#include "Mordhau_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BattleRoyaleGameModeMetadata.BP_BattleRoyaleGameModeMetadata_C
// 0x0000 (0x00E0 - 0x00E0)
class UBP_BattleRoyaleGameModeMetadata_C final : public UGameModeMetadata
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_BattleRoyaleGameModeMetadata_C">();
	}
	static class UBP_BattleRoyaleGameModeMetadata_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_BattleRoyaleGameModeMetadata_C>();
	}
};
static_assert(alignof(UBP_BattleRoyaleGameModeMetadata_C) == 0x000008, "Wrong alignment on UBP_BattleRoyaleGameModeMetadata_C");
static_assert(sizeof(UBP_BattleRoyaleGameModeMetadata_C) == 0x0000E0, "Wrong size on UBP_BattleRoyaleGameModeMetadata_C");

}

