#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CustomizationTab

#include "Basic.hpp"

#include "Mordhau_structs.hpp"
#include "MordhauOnlineSubsystem_structs.hpp"


namespace SDK::Params
{

// Function BP_CustomizationTab.BP_CustomizationTab_C.ExecuteUbergraph_BP_CustomizationTab
// 0x00E8 (0x00E8 - 0x0000)
struct BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPlayFabEntitlements                   K2Node_CustomEvent_UpdatedEntitlements;            // 0x0008(0x0020)()
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0028(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(const struct FPlayFabEntitlements& UpdatedEntitlements)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x0038(0x0010)(ZeroConstructor, NoDestructor)
	class AMordhauHUD*                            CallFunc_GetMordhauHUD_ReturnValue;                // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_MordhauHUD_C*                       K2Node_DynamicCast_AsBP_Mordhau_HUD;               // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0058(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_MainMenu_C*                         K2Node_DynamicCast_AsBP_Main_Menu;                 // 0x0068(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AHUD*                                   CallFunc_GetHUD_ReturnValue;                       // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_MordhauHUD_C*                       K2Node_DynamicCast_AsBP_Mordhau_HUD_1;             // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_89[0x7];                                       // 0x0089(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AMordhauHUD*                            CallFunc_GetMordhauHUD_ReturnValue_1;              // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AMordhauHUD*                            CallFunc_GetMordhauHUD_ReturnValue_2;              // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_MordhauHUD_C*                       K2Node_DynamicCast_AsBP_Mordhau_HUD_2;             // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A9[0x7];                                       // 0x00A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_MordhauHUD_C*                       K2Node_DynamicCast_AsBP_Mordhau_HUD_3;             // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B9[0x7];                                       // 0x00B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_MainMenu_C*                         K2Node_DynamicCast_AsBP_Main_Menu_1;               // 0x00C0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C9[0x7];                                       // 0x00C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_MainMenu_C*                         K2Node_DynamicCast_AsBP_Main_Menu_2;               // 0x00D0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_6;                     // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00D9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_DA[0x6];                                       // 0x00DA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UBP_ChoiceDialog_C*                     CallFunc_CreateChoiceDialog_ChoiceDialog;          // 0x00E0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab) == 0x000008, "Wrong alignment on BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab");
static_assert(sizeof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab) == 0x0000E8, "Wrong size on BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, EntryPoint) == 0x000000, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, K2Node_CustomEvent_UpdatedEntitlements) == 0x000008, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::K2Node_CustomEvent_UpdatedEntitlements' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, K2Node_CreateDelegate_OutputDelegate) == 0x000028, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, K2Node_CreateDelegate_OutputDelegate_1) == 0x000038, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, CallFunc_GetMordhauHUD_ReturnValue) == 0x000048, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::CallFunc_GetMordhauHUD_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, K2Node_DynamicCast_AsBP_Mordhau_HUD) == 0x000050, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::K2Node_DynamicCast_AsBP_Mordhau_HUD' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, K2Node_DynamicCast_bSuccess) == 0x000058, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, CallFunc_GetPlayerController_ReturnValue) == 0x000060, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, K2Node_DynamicCast_AsBP_Main_Menu) == 0x000068, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::K2Node_DynamicCast_AsBP_Main_Menu' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, K2Node_DynamicCast_bSuccess_1) == 0x000070, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, CallFunc_GetHUD_ReturnValue) == 0x000078, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::CallFunc_GetHUD_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, K2Node_DynamicCast_AsBP_Mordhau_HUD_1) == 0x000080, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::K2Node_DynamicCast_AsBP_Mordhau_HUD_1' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, K2Node_DynamicCast_bSuccess_2) == 0x000088, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, CallFunc_GetMordhauHUD_ReturnValue_1) == 0x000090, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::CallFunc_GetMordhauHUD_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, CallFunc_GetMordhauHUD_ReturnValue_2) == 0x000098, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::CallFunc_GetMordhauHUD_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, K2Node_DynamicCast_AsBP_Mordhau_HUD_2) == 0x0000A0, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::K2Node_DynamicCast_AsBP_Mordhau_HUD_2' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, K2Node_DynamicCast_bSuccess_3) == 0x0000A8, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, K2Node_DynamicCast_AsBP_Mordhau_HUD_3) == 0x0000B0, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::K2Node_DynamicCast_AsBP_Mordhau_HUD_3' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, K2Node_DynamicCast_bSuccess_4) == 0x0000B8, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, K2Node_DynamicCast_AsBP_Main_Menu_1) == 0x0000C0, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::K2Node_DynamicCast_AsBP_Main_Menu_1' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, K2Node_DynamicCast_bSuccess_5) == 0x0000C8, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::K2Node_DynamicCast_bSuccess_5' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, K2Node_DynamicCast_AsBP_Main_Menu_2) == 0x0000D0, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::K2Node_DynamicCast_AsBP_Main_Menu_2' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, K2Node_DynamicCast_bSuccess_6) == 0x0000D8, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::K2Node_DynamicCast_bSuccess_6' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, CallFunc_IsValid_ReturnValue) == 0x0000D9, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab, CallFunc_CreateChoiceDialog_ChoiceDialog) == 0x0000E0, "Member 'BP_CustomizationTab_C_ExecuteUbergraph_BP_CustomizationTab::CallFunc_CreateChoiceDialog_ChoiceDialog' has a wrong offset!");

// Function BP_CustomizationTab.BP_CustomizationTab_C.OnDLCUpdateRecevied
// 0x0020 (0x0020 - 0x0000)
struct BP_CustomizationTab_C_OnDLCUpdateRecevied final
{
public:
	struct FPlayFabEntitlements                   UpdatedEntitlements;                               // 0x0000(0x0020)(BlueprintVisible, BlueprintReadOnly, Parm)
};
static_assert(alignof(BP_CustomizationTab_C_OnDLCUpdateRecevied) == 0x000008, "Wrong alignment on BP_CustomizationTab_C_OnDLCUpdateRecevied");
static_assert(sizeof(BP_CustomizationTab_C_OnDLCUpdateRecevied) == 0x000020, "Wrong size on BP_CustomizationTab_C_OnDLCUpdateRecevied");
static_assert(offsetof(BP_CustomizationTab_C_OnDLCUpdateRecevied, UpdatedEntitlements) == 0x000000, "Member 'BP_CustomizationTab_C_OnDLCUpdateRecevied::UpdatedEntitlements' has a wrong offset!");

// Function BP_CustomizationTab.BP_CustomizationTab_C.SetActive
// 0x0010 (0x0010 - 0x0000)
struct BP_CustomizationTab_C_SetActive final
{
public:
	class ABP_MordhauCustomizationPlatform_C*     CallFunc_GetCustomizationPlatform_Platform;        // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_CustomizationTab_C_SetActive) == 0x000008, "Wrong alignment on BP_CustomizationTab_C_SetActive");
static_assert(sizeof(BP_CustomizationTab_C_SetActive) == 0x000010, "Wrong size on BP_CustomizationTab_C_SetActive");
static_assert(offsetof(BP_CustomizationTab_C_SetActive, CallFunc_GetCustomizationPlatform_Platform) == 0x000000, "Member 'BP_CustomizationTab_C_SetActive::CallFunc_GetCustomizationPlatform_Platform' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_SetActive, CallFunc_IsValid_ReturnValue) == 0x000008, "Member 'BP_CustomizationTab_C_SetActive::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function BP_CustomizationTab.BP_CustomizationTab_C.OnCharacterDollUpdated
// 0x0008 (0x0008 - 0x0000)
struct BP_CustomizationTab_C_OnCharacterDollUpdated final
{
public:
	class AMordhauCharacter*                      Character;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CustomizationTab_C_OnCharacterDollUpdated) == 0x000008, "Wrong alignment on BP_CustomizationTab_C_OnCharacterDollUpdated");
static_assert(sizeof(BP_CustomizationTab_C_OnCharacterDollUpdated) == 0x000008, "Wrong size on BP_CustomizationTab_C_OnCharacterDollUpdated");
static_assert(offsetof(BP_CustomizationTab_C_OnCharacterDollUpdated, Character) == 0x000000, "Member 'BP_CustomizationTab_C_OnCharacterDollUpdated::Character' has a wrong offset!");

// Function BP_CustomizationTab.BP_CustomizationTab_C.GetCustomizationPlatform
// 0x0010 (0x0010 - 0x0000)
struct BP_CustomizationTab_C_GetCustomizationPlatform final
{
public:
	class ABP_MordhauCustomizationPlatform_C*     Platform;                                          // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_CustomizationTab_C_GetCustomizationPlatform) == 0x000008, "Wrong alignment on BP_CustomizationTab_C_GetCustomizationPlatform");
static_assert(sizeof(BP_CustomizationTab_C_GetCustomizationPlatform) == 0x000010, "Wrong size on BP_CustomizationTab_C_GetCustomizationPlatform");
static_assert(offsetof(BP_CustomizationTab_C_GetCustomizationPlatform, Platform) == 0x000000, "Member 'BP_CustomizationTab_C_GetCustomizationPlatform::Platform' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_GetCustomizationPlatform, CallFunc_IsValid_ReturnValue) == 0x000008, "Member 'BP_CustomizationTab_C_GetCustomizationPlatform::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function BP_CustomizationTab.BP_CustomizationTab_C.CreateCharacterDoll
// 0x0010 (0x0010 - 0x0000)
struct BP_CustomizationTab_C_CreateCharacterDoll final
{
public:
	class ABP_MordhauCustomizationPlatform_C*     CallFunc_GetCustomizationPlatform_Platform;        // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_CustomizationTab_C_CreateCharacterDoll) == 0x000008, "Wrong alignment on BP_CustomizationTab_C_CreateCharacterDoll");
static_assert(sizeof(BP_CustomizationTab_C_CreateCharacterDoll) == 0x000010, "Wrong size on BP_CustomizationTab_C_CreateCharacterDoll");
static_assert(offsetof(BP_CustomizationTab_C_CreateCharacterDoll, CallFunc_GetCustomizationPlatform_Platform) == 0x000000, "Member 'BP_CustomizationTab_C_CreateCharacterDoll::CallFunc_GetCustomizationPlatform_Platform' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_CreateCharacterDoll, CallFunc_IsValid_ReturnValue) == 0x000008, "Member 'BP_CustomizationTab_C_CreateCharacterDoll::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function BP_CustomizationTab.BP_CustomizationTab_C.UnequipWearableSlot
// 0x0002 (0x0002 - 0x0000)
struct BP_CustomizationTab_C_UnequipWearableSlot final
{
public:
	EWearableSlot                                 Slot_0;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_CustomizationTab_C_UnequipWearableSlot) == 0x000001, "Wrong alignment on BP_CustomizationTab_C_UnequipWearableSlot");
static_assert(sizeof(BP_CustomizationTab_C_UnequipWearableSlot) == 0x000002, "Wrong size on BP_CustomizationTab_C_UnequipWearableSlot");
static_assert(offsetof(BP_CustomizationTab_C_UnequipWearableSlot, Slot_0) == 0x000000, "Member 'BP_CustomizationTab_C_UnequipWearableSlot::Slot_0' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_UnequipWearableSlot, CallFunc_IsValid_ReturnValue) == 0x000001, "Member 'BP_CustomizationTab_C_UnequipWearableSlot::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function BP_CustomizationTab.BP_CustomizationTab_C.UnequipEquipmentSlot
// 0x0008 (0x0008 - 0x0000)
struct BP_CustomizationTab_C_UnequipEquipmentSlot final
{
public:
	int32                                         Slot_0;                                            // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_Conv_IntToByte_ReturnValue;               // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_CustomizationTab_C_UnequipEquipmentSlot) == 0x000004, "Wrong alignment on BP_CustomizationTab_C_UnequipEquipmentSlot");
static_assert(sizeof(BP_CustomizationTab_C_UnequipEquipmentSlot) == 0x000008, "Wrong size on BP_CustomizationTab_C_UnequipEquipmentSlot");
static_assert(offsetof(BP_CustomizationTab_C_UnequipEquipmentSlot, Slot_0) == 0x000000, "Member 'BP_CustomizationTab_C_UnequipEquipmentSlot::Slot_0' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_UnequipEquipmentSlot, CallFunc_Conv_IntToByte_ReturnValue) == 0x000004, "Member 'BP_CustomizationTab_C_UnequipEquipmentSlot::CallFunc_Conv_IntToByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_UnequipEquipmentSlot, CallFunc_IsValid_ReturnValue) == 0x000005, "Member 'BP_CustomizationTab_C_UnequipEquipmentSlot::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function BP_CustomizationTab.BP_CustomizationTab_C.UnequipPerk
// 0x0010 (0x0010 - 0x0000)
struct BP_CustomizationTab_C_UnequipPerk final
{
public:
	class UClass*                                 Perk;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_CustomizationTab_C_UnequipPerk) == 0x000008, "Wrong alignment on BP_CustomizationTab_C_UnequipPerk");
static_assert(sizeof(BP_CustomizationTab_C_UnequipPerk) == 0x000010, "Wrong size on BP_CustomizationTab_C_UnequipPerk");
static_assert(offsetof(BP_CustomizationTab_C_UnequipPerk, Perk) == 0x000000, "Member 'BP_CustomizationTab_C_UnequipPerk::Perk' has a wrong offset!");
static_assert(offsetof(BP_CustomizationTab_C_UnequipPerk, CallFunc_IsValid_ReturnValue) == 0x000008, "Member 'BP_CustomizationTab_C_UnequipPerk::CallFunc_IsValid_ReturnValue' has a wrong offset!");

}

