#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CatapultProjectile

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_MordhauProjectile_classes.hpp"
#include "Mordhau_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CatapultProjectile.BP_CatapultProjectile_C
// 0x0010 (0x0870 - 0x0860)
#pragma pack(push, 0x1)
class alignas(0x10) ABP_CatapultProjectile_C : public ABP_MordhauProjectile_C
{
public:
	uint8                                         Pad_854[0x4];                                      // 0x0854(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_CatapultProjectile_C;            // 0x0858(0x0008)(ZeroConstructor, Transient, DuplicateTransient, UObjectWrapper)
	class AMordhauCharacter*                      KilledChar;                                        // 0x0860(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_CatapultProjectile(int32 EntryPoint);
	void OnUsedToKillOther(class AAdvancedCharacter* Character, EMordhauDamageType Type, uint8 SubType, class FName bone, const struct FVector& Point, class AActor* Source);
	void Fire();
	void OnProjectileHit(const struct FVector& HitLocation, const struct FVector& HitNormal, float BounceForce, uint8 Surface, bool bHasHitWorld, bool bHasStopped);
	void SetProjectileInitialSpeed(uint8 InByte);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CatapultProjectile_C">();
	}
	static class ABP_CatapultProjectile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CatapultProjectile_C>();
	}
};
#pragma pack(pop)
static_assert(alignof(ABP_CatapultProjectile_C) == 0x000010, "Wrong alignment on ABP_CatapultProjectile_C");
static_assert(sizeof(ABP_CatapultProjectile_C) == 0x000870, "Wrong size on ABP_CatapultProjectile_C");
static_assert(offsetof(ABP_CatapultProjectile_C, UberGraphFrame_BP_CatapultProjectile_C) == 0x000858, "Member 'ABP_CatapultProjectile_C::UberGraphFrame_BP_CatapultProjectile_C' has a wrong offset!");
static_assert(offsetof(ABP_CatapultProjectile_C, KilledChar) == 0x000860, "Member 'ABP_CatapultProjectile_C::KilledChar' has a wrong offset!");

}

