#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CrudeChausses

#include "Basic.hpp"

#include "BP_Tier3LegsWearable_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CrudeChausses.BP_CrudeChausses_C
// 0x0000 (0x0240 - 0x0240)
class UBP_CrudeChausses_C final : public UBP_Tier3LegsWearable_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CrudeChausses_C">();
	}
	static class UBP_CrudeChausses_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CrudeChausses_C>();
	}
};
static_assert(alignof(UBP_CrudeChausses_C) == 0x000008, "Wrong alignment on UBP_CrudeChausses_C");
static_assert(sizeof(UBP_CrudeChausses_C) == 0x000240, "Wrong size on UBP_CrudeChausses_C");

}

