#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DemonHordeEnemy_Special_Skeleton

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Mordhau_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_DemonHordeEnemy_Special_Skeleton.BP_DemonHordeEnemy_Special_Skeleton_C.ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton
// 0x02C8 (0x02C8 - 0x0000)
struct BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_LessEqual_IntInt_ReturnValue;             // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0024(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0038(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x3];                                       // 0x0041(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable_1;                               // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue_1;               // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49[0x3];                                       // 0x0049(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable_2;                               // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue_2;               // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_51[0x3];                                       // 0x0051(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_Event_HitResult;                            // 0x0054(0x008C)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class AMordhauCharacter*                      K2Node_Event_Attacker;                             // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue_3;               // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E9[0x7];                                       // 0x00E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AController*                            CallFunc_GetControllerIncludingVehicle_ReturnValue; // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_DemonHordeCharacter_C*              K2Node_DynamicCast_AsBP_Demon_Horde_Character;     // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_101[0x7];                                      // 0x0101(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMordhauMotion*                         CallFunc_GetMotion_ReturnValue;                    // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_KickMotion_C*                       K2Node_DynamicCast_AsBP_Kick_Motion;               // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Trip_ReturnValue;                         // 0x0119(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11A[0x2];                                      // 0x011A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_MordhauTakeDamage_ReturnValue;            // 0x011C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_RandomIntegerInRange_ReturnValue;         // 0x0120(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_RandomFloatInRange_ReturnValue;           // 0x0124(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_3;                               // 0x0128(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Select_Default;                             // 0x012C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         CallFunc_Conv_IntToByte_ReturnValue;               // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_131[0x3];                                      // 0x0131(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0134(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_X;                            // 0x0140(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Y;                            // 0x0144(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector_Z;                            // 0x0148(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_K2_GetActorRotation_ReturnValue;          // 0x014C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x0158(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x015C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x0168(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_174[0x4];                                      // 0x0174(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue;       // 0x0178(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue_4;               // 0x0180(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_181[0x3];                                      // 0x0181(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_MakeHitResult_ReturnValue;                // 0x0184(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	float                                         CallFunc_MordhauTakeDamage_ReturnValue_1;          // 0x0210(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_214[0x4];                                      // 0x0214(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AGameStateBase*                         CallFunc_GetGameState_ReturnValue;                 // 0x0218(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_ByteByte_ReturnValue;                // 0x0220(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_221[0x7];                                      // 0x0221(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_DemonHordeGamestate_C*              K2Node_DynamicCast_AsBP_Demon_Horde_Gamestate;     // 0x0228(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0230(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_231[0x3];                                      // 0x0231(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_MakeHitResult_ReturnValue_1;              // 0x0234(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	float                                         CallFunc_MordhauTakeDamage_ReturnValue_2;          // 0x02C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton) == 0x000008, "Wrong alignment on BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton");
static_assert(sizeof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton) == 0x0002C8, "Wrong size on BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, EntryPoint) == 0x000000, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, Temp_int_Variable) == 0x000004, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, K2Node_CreateDelegate_OutputDelegate) == 0x000008, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_LessEqual_IntInt_ReturnValue) == 0x000018, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_LessEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_Add_IntInt_ReturnValue) == 0x00001C, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, Temp_bool_Variable) == 0x000020, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, K2Node_CreateDelegate_OutputDelegate_1) == 0x000024, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000038, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_HasAuthority_ReturnValue) == 0x000040, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, Temp_int_Variable_1) == 0x000044, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_HasAuthority_ReturnValue_1) == 0x000048, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_HasAuthority_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, Temp_int_Variable_2) == 0x00004C, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::Temp_int_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_HasAuthority_ReturnValue_2) == 0x000050, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_HasAuthority_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, K2Node_Event_HitResult) == 0x000054, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::K2Node_Event_HitResult' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, K2Node_Event_Attacker) == 0x0000E0, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::K2Node_Event_Attacker' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_HasAuthority_ReturnValue_3) == 0x0000E8, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_HasAuthority_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_GetControllerIncludingVehicle_ReturnValue) == 0x0000F0, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_GetControllerIncludingVehicle_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, K2Node_DynamicCast_AsBP_Demon_Horde_Character) == 0x0000F8, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::K2Node_DynamicCast_AsBP_Demon_Horde_Character' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, K2Node_DynamicCast_bSuccess) == 0x000100, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_GetMotion_ReturnValue) == 0x000108, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_GetMotion_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, K2Node_DynamicCast_AsBP_Kick_Motion) == 0x000110, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::K2Node_DynamicCast_AsBP_Kick_Motion' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, K2Node_DynamicCast_bSuccess_1) == 0x000118, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_Trip_ReturnValue) == 0x000119, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_Trip_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_MordhauTakeDamage_ReturnValue) == 0x00011C, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_MordhauTakeDamage_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_RandomIntegerInRange_ReturnValue) == 0x000120, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_RandomIntegerInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_RandomFloatInRange_ReturnValue) == 0x000124, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_RandomFloatInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, Temp_int_Variable_3) == 0x000128, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::Temp_int_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, K2Node_Select_Default) == 0x00012C, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_Conv_IntToByte_ReturnValue) == 0x000130, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_Conv_IntToByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000134, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_BreakVector_X) == 0x000140, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_BreakVector_Y) == 0x000144, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_BreakVector_Z) == 0x000148, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_K2_GetActorRotation_ReturnValue) == 0x00014C, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_K2_GetActorRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x000158, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x00015C, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_MakeVector_ReturnValue) == 0x000168, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_SpawnEmitterAtLocation_ReturnValue) == 0x000178, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_SpawnEmitterAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_HasAuthority_ReturnValue_4) == 0x000180, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_HasAuthority_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_MakeHitResult_ReturnValue) == 0x000184, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_MakeHitResult_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_MordhauTakeDamage_ReturnValue_1) == 0x000210, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_MordhauTakeDamage_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_GetGameState_ReturnValue) == 0x000218, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_GetGameState_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_Less_ByteByte_ReturnValue) == 0x000220, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_Less_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, K2Node_DynamicCast_AsBP_Demon_Horde_Gamestate) == 0x000228, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::K2Node_DynamicCast_AsBP_Demon_Horde_Gamestate' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, K2Node_DynamicCast_bSuccess_2) == 0x000230, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_MakeHitResult_ReturnValue_1) == 0x000234, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_MakeHitResult_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton, CallFunc_MordhauTakeDamage_ReturnValue_2) == 0x0002C0, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ExecuteUbergraph_BP_DemonHordeEnemy_Special_Skeleton::CallFunc_MordhauTakeDamage_ReturnValue_2' has a wrong offset!");

// Function BP_DemonHordeEnemy_Special_Skeleton.BP_DemonHordeEnemy_Special_Skeleton_C.OnBlockedMelee
// 0x0098 (0x0098 - 0x0000)
struct BP_DemonHordeEnemy_Special_Skeleton_C_OnBlockedMelee final
{
public:
	struct FHitResult                             HitResult;                                         // 0x0000(0x008C)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	uint8                                         Pad_8C[0x4];                                       // 0x008C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AMordhauCharacter*                      Attacker;                                          // 0x0090(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_DemonHordeEnemy_Special_Skeleton_C_OnBlockedMelee) == 0x000008, "Wrong alignment on BP_DemonHordeEnemy_Special_Skeleton_C_OnBlockedMelee");
static_assert(sizeof(BP_DemonHordeEnemy_Special_Skeleton_C_OnBlockedMelee) == 0x000098, "Wrong size on BP_DemonHordeEnemy_Special_Skeleton_C_OnBlockedMelee");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_OnBlockedMelee, HitResult) == 0x000000, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_OnBlockedMelee::HitResult' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_OnBlockedMelee, Attacker) == 0x000090, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_OnBlockedMelee::Attacker' has a wrong offset!");

// Function BP_DemonHordeEnemy_Special_Skeleton.BP_DemonHordeEnemy_Special_Skeleton_C.OnRep_Visible
// 0x0010 (0x0010 - 0x0000)
struct BP_DemonHordeEnemy_Special_Skeleton_C_OnRep_Visible final
{
public:
	bool                                          Temp_bool_Variable;                                // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Temp_float_Variable;                               // 0x0004(0x0004)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_1;                             // 0x0008(0x0004)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Select_Default;                             // 0x000C(0x0004)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_DemonHordeEnemy_Special_Skeleton_C_OnRep_Visible) == 0x000004, "Wrong alignment on BP_DemonHordeEnemy_Special_Skeleton_C_OnRep_Visible");
static_assert(sizeof(BP_DemonHordeEnemy_Special_Skeleton_C_OnRep_Visible) == 0x000010, "Wrong size on BP_DemonHordeEnemy_Special_Skeleton_C_OnRep_Visible");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_OnRep_Visible, Temp_bool_Variable) == 0x000000, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_OnRep_Visible::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_OnRep_Visible, Temp_float_Variable) == 0x000004, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_OnRep_Visible::Temp_float_Variable' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_OnRep_Visible, Temp_float_Variable_1) == 0x000008, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_OnRep_Visible::Temp_float_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_OnRep_Visible, K2Node_Select_Default) == 0x00000C, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_OnRep_Visible::K2Node_Select_Default' has a wrong offset!");

// Function BP_DemonHordeEnemy_Special_Skeleton.BP_DemonHordeEnemy_Special_Skeleton_C.ModifyDamage
// 0x00F8 (0x00F8 - 0x0000)
struct BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage final
{
public:
	float                                         DamageAmount;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMordhauDamageInfo                     DamageInfo;                                        // 0x0008(0x00A8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference)
	class AController*                            EventInstigator;                                   // 0x00B0(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         ReturnValue;                                       // 0x00B8(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable;                               // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_ModifyDamage_ReturnValue;                 // 0x00C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x00C4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C5[0x3];                                       // 0x00C5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_DemonHordeCharacter_C*              K2Node_DynamicCast_AsBP_Demon_Horde_Character;     // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x00D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D2[0x2];                                       // 0x00D2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Select_Default;                             // 0x00D4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D9[0x3];                                       // 0x00D9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x00DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMordhauMotion*                         CallFunc_GetMotion_ReturnValue;                    // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_KickMotion_C*                       K2Node_DynamicCast_AsBP_Kick_Motion;               // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage) == 0x000008, "Wrong alignment on BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage");
static_assert(sizeof(BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage) == 0x0000F8, "Wrong size on BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage, DamageAmount) == 0x000000, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage::DamageAmount' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage, DamageInfo) == 0x000008, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage::DamageInfo' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage, EventInstigator) == 0x0000B0, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage::EventInstigator' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage, ReturnValue) == 0x0000B8, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage, Temp_float_Variable) == 0x0000BC, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage::Temp_float_Variable' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage, CallFunc_ModifyDamage_ReturnValue) == 0x0000C0, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage::CallFunc_ModifyDamage_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage, Temp_bool_Variable) == 0x0000C4, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage, K2Node_DynamicCast_AsBP_Demon_Horde_Character) == 0x0000C8, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage::K2Node_DynamicCast_AsBP_Demon_Horde_Character' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage, K2Node_DynamicCast_bSuccess) == 0x0000D0, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x0000D1, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage, K2Node_Select_Default) == 0x0000D4, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage, CallFunc_IsValid_ReturnValue) == 0x0000D8, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x0000DC, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage, CallFunc_GetMotion_ReturnValue) == 0x0000E0, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage::CallFunc_GetMotion_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage, K2Node_DynamicCast_AsBP_Kick_Motion) == 0x0000E8, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage::K2Node_DynamicCast_AsBP_Kick_Motion' has a wrong offset!");
static_assert(offsetof(BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage, K2Node_DynamicCast_bSuccess_1) == 0x0000F0, "Member 'BP_DemonHordeEnemy_Special_Skeleton_C_ModifyDamage::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");

}

