#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DemonVoice

#include "Basic.hpp"

#include "Mordhau_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DemonVoice.BP_DemonVoice_C
// 0x0000 (0x00A8 - 0x00A8)
class UBP_DemonVoice_C : public UCharacterVoice
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_DemonVoice_C">();
	}
	static class UBP_DemonVoice_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_DemonVoice_C>();
	}
};
static_assert(alignof(UBP_DemonVoice_C) == 0x000008, "Wrong alignment on UBP_DemonVoice_C");
static_assert(sizeof(UBP_DemonVoice_C) == 0x0000A8, "Wrong size on UBP_DemonVoice_C");

}

