#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EmoteCancelMotion

#include "Basic.hpp"

#include "Mordhau_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_EmoteCancelMotion.BP_EmoteCancelMotion_C
// 0x0000 (0x00A0 - 0x00A0)
class UBP_EmoteCancelMotion_C final : public UEmoteCancelMotion
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_EmoteCancelMotion_C">();
	}
	static class UBP_EmoteCancelMotion_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_EmoteCancelMotion_C>();
	}
};
static_assert(alignof(UBP_EmoteCancelMotion_C) == 0x000008, "Wrong alignment on UBP_EmoteCancelMotion_C");
static_assert(sizeof(UBP_EmoteCancelMotion_C) == 0x0000A0, "Wrong size on UBP_EmoteCancelMotion_C");

}

