#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EquipmentFilterTabTooltip

#include "Basic.hpp"

#include "BP_Tooltip_classes.hpp"
#include "UMG_structs.hpp"
#include "Mordhau_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_EquipmentFilterTabTooltip.BP_EquipmentFilterTabTooltip_C
// 0x0040 (0x02A0 - 0x0260)
class UBP_EquipmentFilterTabTooltip_C final : public UBP_Tooltip_C
{
public:
	class UBP_EquipmentTypeIndicator_C*           BP_EquipmentTypeIndicator;                         // 0x0260(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_FilterTooltipHasSelectedItem_C*     BP_FilterTooltipHasSelectedItem_237;               // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image;                                             // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_89;                                          // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_316;                                         // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class URichTextBlock*                         TextBlock_Description;                             // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_Name;                                    // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          Has_Selected_Item;                                 // 0x0298(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void Update_Tooltip(const class FText& Title_Text, const class FText& Decription_Text, EEquipmentCategory Category, bool bHasSelectedItem, class UBP_EquipmentFilterTabTooltip_C** Toolip);
	ESlateVisibility GetVisibility_0();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_EquipmentFilterTabTooltip_C">();
	}
	static class UBP_EquipmentFilterTabTooltip_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_EquipmentFilterTabTooltip_C>();
	}
};
static_assert(alignof(UBP_EquipmentFilterTabTooltip_C) == 0x000008, "Wrong alignment on UBP_EquipmentFilterTabTooltip_C");
static_assert(sizeof(UBP_EquipmentFilterTabTooltip_C) == 0x0002A0, "Wrong size on UBP_EquipmentFilterTabTooltip_C");
static_assert(offsetof(UBP_EquipmentFilterTabTooltip_C, BP_EquipmentTypeIndicator) == 0x000260, "Member 'UBP_EquipmentFilterTabTooltip_C::BP_EquipmentTypeIndicator' has a wrong offset!");
static_assert(offsetof(UBP_EquipmentFilterTabTooltip_C, BP_FilterTooltipHasSelectedItem_237) == 0x000268, "Member 'UBP_EquipmentFilterTabTooltip_C::BP_FilterTooltipHasSelectedItem_237' has a wrong offset!");
static_assert(offsetof(UBP_EquipmentFilterTabTooltip_C, Image) == 0x000270, "Member 'UBP_EquipmentFilterTabTooltip_C::Image' has a wrong offset!");
static_assert(offsetof(UBP_EquipmentFilterTabTooltip_C, Image_89) == 0x000278, "Member 'UBP_EquipmentFilterTabTooltip_C::Image_89' has a wrong offset!");
static_assert(offsetof(UBP_EquipmentFilterTabTooltip_C, Image_316) == 0x000280, "Member 'UBP_EquipmentFilterTabTooltip_C::Image_316' has a wrong offset!");
static_assert(offsetof(UBP_EquipmentFilterTabTooltip_C, TextBlock_Description) == 0x000288, "Member 'UBP_EquipmentFilterTabTooltip_C::TextBlock_Description' has a wrong offset!");
static_assert(offsetof(UBP_EquipmentFilterTabTooltip_C, TextBlock_Name) == 0x000290, "Member 'UBP_EquipmentFilterTabTooltip_C::TextBlock_Name' has a wrong offset!");
static_assert(offsetof(UBP_EquipmentFilterTabTooltip_C, Has_Selected_Item) == 0x000298, "Member 'UBP_EquipmentFilterTabTooltip_C::Has_Selected_Item' has a wrong offset!");

}

