#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Estoc_Hunter

#include "Basic.hpp"

#include "BP_Estoc_Hunter_classes.hpp"
#include "BP_Estoc_Hunter_parameters.hpp"


namespace SDK
{

// Function BP_Estoc_Hunter.BP_Estoc_Hunter_C.ExecuteUbergraph_BP_Estoc_Hunter
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Estoc_Hunter_C::ExecuteUbergraph_BP_Estoc_Hunter(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Estoc_Hunter_C", "ExecuteUbergraph_BP_Estoc_Hunter");

	Params::BP_Estoc_Hunter_C_ExecuteUbergraph_BP_Estoc_Hunter Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Estoc_Hunter.BP_Estoc_Hunter_C.ReceiveTick
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Estoc_Hunter_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Estoc_Hunter_C", "ReceiveTick");

	Params::BP_Estoc_Hunter_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Estoc_Hunter.BP_Estoc_Hunter_C.ReceiveActorBeginOverlap
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Estoc_Hunter_C::ReceiveActorBeginOverlap(class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Estoc_Hunter_C", "ReceiveActorBeginOverlap");

	Params::BP_Estoc_Hunter_C_ReceiveActorBeginOverlap Parms{};

	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Estoc_Hunter.BP_Estoc_Hunter_C.ReceiveBeginPlay
// (BlueprintCallable, BlueprintEvent)

void UBP_Estoc_Hunter_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Estoc_Hunter_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

