#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EquipmentItemEntry

#include "Basic.hpp"

#include "BP_EquipmentItemEntry_classes.hpp"
#include "BP_EquipmentItemEntry_parameters.hpp"


namespace SDK
{

// Function BP_EquipmentItemEntry.BP_EquipmentItemEntry_C.ExecuteUbergraph_BP_EquipmentItemEntry
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_EquipmentItemEntry_C::ExecuteUbergraph_BP_EquipmentItemEntry(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EquipmentItemEntry_C", "ExecuteUbergraph_BP_EquipmentItemEntry");

	Params::BP_EquipmentItemEntry_C_ExecuteUbergraph_BP_EquipmentItemEntry Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EquipmentItemEntry.BP_EquipmentItemEntry_C.BndEvt__BP_EquipmentItemEntry_Button_0_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UBP_EquipmentItemEntry_C::BndEvt__BP_EquipmentItemEntry_Button_0_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EquipmentItemEntry_C", "BndEvt__BP_EquipmentItemEntry_Button_0_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EquipmentItemEntry.BP_EquipmentItemEntry_C.Equipment Unlocked
// (BlueprintCallable, BlueprintEvent)

void UBP_EquipmentItemEntry_C::Equipment_Unlocked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EquipmentItemEntry_C", "Equipment Unlocked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EquipmentItemEntry.BP_EquipmentItemEntry_C.BndEvt__Button_0_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UBP_EquipmentItemEntry_C::BndEvt__Button_0_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EquipmentItemEntry_C", "BndEvt__Button_0_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EquipmentItemEntry.BP_EquipmentItemEntry_C.BndEvt__Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBP_EquipmentItemEntry_C::BndEvt__Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EquipmentItemEntry_C", "BndEvt__Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EquipmentItemEntry.BP_EquipmentItemEntry_C.Hide Unlock Indicator
// (BlueprintCallable, BlueprintEvent)

void UBP_EquipmentItemEntry_C::Hide_Unlock_Indicator()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EquipmentItemEntry_C", "Hide Unlock Indicator");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EquipmentItemEntry.BP_EquipmentItemEntry_C.RefreshWidget
// (BlueprintCallable, BlueprintEvent)

void UBP_EquipmentItemEntry_C::RefreshWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EquipmentItemEntry_C", "RefreshWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EquipmentItemEntry.BP_EquipmentItemEntry_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_EquipmentItemEntry_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EquipmentItemEntry_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EquipmentItemEntry.BP_EquipmentItemEntry_C.Initialize Equipment Entry
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_EquipmentItemEntry_C::Initialize_Equipment_Entry()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EquipmentItemEntry_C", "Initialize Equipment Entry");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EquipmentItemEntry.BP_EquipmentItemEntry_C.Get_CostText_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UBP_EquipmentItemEntry_C::Get_CostText_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EquipmentItemEntry_C", "Get_CostText_Text_0");

	Params::BP_EquipmentItemEntry_C_Get_CostText_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_EquipmentItemEntry.BP_EquipmentItemEntry_C.Get_CostAndIconBox_Visibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UBP_EquipmentItemEntry_C::Get_CostAndIconBox_Visibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EquipmentItemEntry_C", "Get_CostAndIconBox_Visibility_0");

	Params::BP_EquipmentItemEntry_C_Get_CostAndIconBox_Visibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_EquipmentItemEntry.BP_EquipmentItemEntry_C.Get_ic_locked_Visibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UBP_EquipmentItemEntry_C::Get_ic_locked_Visibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EquipmentItemEntry_C", "Get_ic_locked_Visibility_0");

	Params::BP_EquipmentItemEntry_C_Get_ic_locked_Visibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_EquipmentItemEntry.BP_EquipmentItemEntry_C.Get_GradientOverlay_ColorAndOpacity_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UBP_EquipmentItemEntry_C::Get_GradientOverlay_ColorAndOpacity_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EquipmentItemEntry_C", "Get_GradientOverlay_ColorAndOpacity_0");

	Params::BP_EquipmentItemEntry_C_Get_GradientOverlay_ColorAndOpacity_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_EquipmentItemEntry.BP_EquipmentItemEntry_C.Get_Image_10_ColorAndOpacity_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UBP_EquipmentItemEntry_C::Get_Image_10_ColorAndOpacity_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EquipmentItemEntry_C", "Get_Image_10_ColorAndOpacity_0");

	Params::BP_EquipmentItemEntry_C_Get_Image_10_ColorAndOpacity_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_EquipmentItemEntry.BP_EquipmentItemEntry_C.Update Entry Name
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Param_Name_0                                           (BlueprintVisible, BlueprintReadOnly, Parm)

void UBP_EquipmentItemEntry_C::Update_Entry_Name(const class FText& Param_Name_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EquipmentItemEntry_C", "Update Entry Name");

	Params::BP_EquipmentItemEntry_C_Update_Entry_Name Parms{};

	Parms.Param_Name_0 = std::move(Param_Name_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EquipmentItemEntry.BP_EquipmentItemEntry_C.Update Tooltip Widget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBP_EquipmentTooltip_C*           Tooltip_0                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UBP_EquipmentTooltip_C*           Equipment_Toolip                                       (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_EquipmentItemEntry_C::Update_Tooltip_Widget(class UBP_EquipmentTooltip_C* Tooltip_0, class UBP_EquipmentTooltip_C** Equipment_Toolip)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EquipmentItemEntry_C", "Update Tooltip Widget");

	Params::BP_EquipmentItemEntry_C_Update_Tooltip_Widget Parms{};

	Parms.Tooltip_0 = Tooltip_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Equipment_Toolip != nullptr)
		*Equipment_Toolip = Parms.Equipment_Toolip;
}


// Function BP_EquipmentItemEntry.BP_EquipmentItemEntry_C.Get_Image_ColorAndOpacity_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor UBP_EquipmentItemEntry_C::Get_Image_ColorAndOpacity_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EquipmentItemEntry_C", "Get_Image_ColorAndOpacity_0");

	Params::BP_EquipmentItemEntry_C_Get_Image_ColorAndOpacity_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_EquipmentItemEntry.BP_EquipmentItemEntry_C.GetVisibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UBP_EquipmentItemEntry_C::GetVisibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EquipmentItemEntry_C", "GetVisibility_0");

	Params::BP_EquipmentItemEntry_C_GetVisibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_EquipmentItemEntry.BP_EquipmentItemEntry_C.GetbIsEnabled_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UBP_EquipmentItemEntry_C::GetbIsEnabled_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EquipmentItemEntry_C", "GetbIsEnabled_0");

	Params::BP_EquipmentItemEntry_C_GetbIsEnabled_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_EquipmentItemEntry.BP_EquipmentItemEntry_C.Get_Image_2_Visibility_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UBP_EquipmentItemEntry_C::Get_Image_2_Visibility_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EquipmentItemEntry_C", "Get_Image_2_Visibility_0");

	Params::BP_EquipmentItemEntry_C_Get_Image_2_Visibility_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

