#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ForgiveTeamkillPopup

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_ForgiveTeamkillPopup.BP_ForgiveTeamkillPopup_C
// 0x0068 (0x02C8 - 0x0260)
class UBP_ForgiveTeamkillPopup_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient, UObjectWrapper)
	class UImage*                                 Background;                                        // 0x0268(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                Border_0;                                          // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_ButtonPrompt_C*                     BP_ButtonPrompt_VoteNo;                            // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_ButtonPrompt_C*                     BP_ButtonPrompt_VoteYes;                           // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_PlatformIcon_C*                     BP_PlatformIcon;                                   // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           ChoiceList;                                        // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Container;                                         // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_0;                                       // 0x02A0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FString                                 PlayerName;                                        // 0x02A8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	int32                                         TeamDamage;                                        // 0x02B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2BC[0x4];                                      // 0x02BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AMordhauPlayerState*                    Candidate;                                         // 0x02C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_ForgiveTeamkillPopup(int32 EntryPoint);
	void Construct();
	void Show();
	void Hide();
	class FText Get_TextBlock_0_Text_0();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ForgiveTeamkillPopup_C">();
	}
	static class UBP_ForgiveTeamkillPopup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ForgiveTeamkillPopup_C>();
	}
};
static_assert(alignof(UBP_ForgiveTeamkillPopup_C) == 0x000008, "Wrong alignment on UBP_ForgiveTeamkillPopup_C");
static_assert(sizeof(UBP_ForgiveTeamkillPopup_C) == 0x0002C8, "Wrong size on UBP_ForgiveTeamkillPopup_C");
static_assert(offsetof(UBP_ForgiveTeamkillPopup_C, UberGraphFrame) == 0x000260, "Member 'UBP_ForgiveTeamkillPopup_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_ForgiveTeamkillPopup_C, Background) == 0x000268, "Member 'UBP_ForgiveTeamkillPopup_C::Background' has a wrong offset!");
static_assert(offsetof(UBP_ForgiveTeamkillPopup_C, Border_0) == 0x000270, "Member 'UBP_ForgiveTeamkillPopup_C::Border_0' has a wrong offset!");
static_assert(offsetof(UBP_ForgiveTeamkillPopup_C, BP_ButtonPrompt_VoteNo) == 0x000278, "Member 'UBP_ForgiveTeamkillPopup_C::BP_ButtonPrompt_VoteNo' has a wrong offset!");
static_assert(offsetof(UBP_ForgiveTeamkillPopup_C, BP_ButtonPrompt_VoteYes) == 0x000280, "Member 'UBP_ForgiveTeamkillPopup_C::BP_ButtonPrompt_VoteYes' has a wrong offset!");
static_assert(offsetof(UBP_ForgiveTeamkillPopup_C, BP_PlatformIcon) == 0x000288, "Member 'UBP_ForgiveTeamkillPopup_C::BP_PlatformIcon' has a wrong offset!");
static_assert(offsetof(UBP_ForgiveTeamkillPopup_C, ChoiceList) == 0x000290, "Member 'UBP_ForgiveTeamkillPopup_C::ChoiceList' has a wrong offset!");
static_assert(offsetof(UBP_ForgiveTeamkillPopup_C, Container) == 0x000298, "Member 'UBP_ForgiveTeamkillPopup_C::Container' has a wrong offset!");
static_assert(offsetof(UBP_ForgiveTeamkillPopup_C, TextBlock_0) == 0x0002A0, "Member 'UBP_ForgiveTeamkillPopup_C::TextBlock_0' has a wrong offset!");
static_assert(offsetof(UBP_ForgiveTeamkillPopup_C, PlayerName) == 0x0002A8, "Member 'UBP_ForgiveTeamkillPopup_C::PlayerName' has a wrong offset!");
static_assert(offsetof(UBP_ForgiveTeamkillPopup_C, TeamDamage) == 0x0002B8, "Member 'UBP_ForgiveTeamkillPopup_C::TeamDamage' has a wrong offset!");
static_assert(offsetof(UBP_ForgiveTeamkillPopup_C, Candidate) == 0x0002C0, "Member 'UBP_ForgiveTeamkillPopup_C::Candidate' has a wrong offset!");

}

