#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FriendSearchEntry

#include "Basic.hpp"

#include "MordhauOnlineSubsystem_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function BP_FriendSearchEntry.BP_FriendSearchEntry_C.ExecuteUbergraph_BP_FriendSearchEntry
// 0x0020 (0x0020 - 0x0000)
struct BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bIsExpanded;                          // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7[0x1];                                        // 0x0007(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class UObject*                                K2Node_Event_ListItemObject;                       // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBP_FriendSearchEntryData_C*            K2Node_DynamicCast_AsBP_Friend_Search_Entry_Data;  // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bIsSelected;                          // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x001A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x001B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry) == 0x000008, "Wrong alignment on BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry");
static_assert(sizeof(BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry) == 0x000020, "Wrong size on BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry");
static_assert(offsetof(BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry, EntryPoint) == 0x000000, "Member 'BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry, Temp_byte_Variable) == 0x000004, "Member 'BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry, Temp_byte_Variable_1) == 0x000005, "Member 'BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry, K2Node_Event_bIsExpanded) == 0x000006, "Member 'BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry::K2Node_Event_bIsExpanded' has a wrong offset!");
static_assert(offsetof(BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry, K2Node_Event_ListItemObject) == 0x000008, "Member 'BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry::K2Node_Event_ListItemObject' has a wrong offset!");
static_assert(offsetof(BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry, K2Node_DynamicCast_AsBP_Friend_Search_Entry_Data) == 0x000010, "Member 'BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry::K2Node_DynamicCast_AsBP_Friend_Search_Entry_Data' has a wrong offset!");
static_assert(offsetof(BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry, K2Node_Event_bIsSelected) == 0x000019, "Member 'BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry::K2Node_Event_bIsSelected' has a wrong offset!");
static_assert(offsetof(BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry, Temp_bool_Variable) == 0x00001A, "Member 'BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry, K2Node_Select_Default) == 0x00001B, "Member 'BP_FriendSearchEntry_C_ExecuteUbergraph_BP_FriendSearchEntry::K2Node_Select_Default' has a wrong offset!");

// Function BP_FriendSearchEntry.BP_FriendSearchEntry_C.BP_OnItemSelectionChanged
// 0x0001 (0x0001 - 0x0000)
struct BP_FriendSearchEntry_C_BP_OnItemSelectionChanged final
{
public:
	bool                                          bIsSelected;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_FriendSearchEntry_C_BP_OnItemSelectionChanged) == 0x000001, "Wrong alignment on BP_FriendSearchEntry_C_BP_OnItemSelectionChanged");
static_assert(sizeof(BP_FriendSearchEntry_C_BP_OnItemSelectionChanged) == 0x000001, "Wrong size on BP_FriendSearchEntry_C_BP_OnItemSelectionChanged");
static_assert(offsetof(BP_FriendSearchEntry_C_BP_OnItemSelectionChanged, bIsSelected) == 0x000000, "Member 'BP_FriendSearchEntry_C_BP_OnItemSelectionChanged::bIsSelected' has a wrong offset!");

// Function BP_FriendSearchEntry.BP_FriendSearchEntry_C.OnListItemObjectSet
// 0x0008 (0x0008 - 0x0000)
struct BP_FriendSearchEntry_C_OnListItemObjectSet final
{
public:
	class UObject*                                ListItemObject;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_FriendSearchEntry_C_OnListItemObjectSet) == 0x000008, "Wrong alignment on BP_FriendSearchEntry_C_OnListItemObjectSet");
static_assert(sizeof(BP_FriendSearchEntry_C_OnListItemObjectSet) == 0x000008, "Wrong size on BP_FriendSearchEntry_C_OnListItemObjectSet");
static_assert(offsetof(BP_FriendSearchEntry_C_OnListItemObjectSet, ListItemObject) == 0x000000, "Member 'BP_FriendSearchEntry_C_OnListItemObjectSet::ListItemObject' has a wrong offset!");

// Function BP_FriendSearchEntry.BP_FriendSearchEntry_C.BP_OnItemExpansionChanged
// 0x0001 (0x0001 - 0x0000)
struct BP_FriendSearchEntry_C_BP_OnItemExpansionChanged final
{
public:
	bool                                          bIsExpanded;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_FriendSearchEntry_C_BP_OnItemExpansionChanged) == 0x000001, "Wrong alignment on BP_FriendSearchEntry_C_BP_OnItemExpansionChanged");
static_assert(sizeof(BP_FriendSearchEntry_C_BP_OnItemExpansionChanged) == 0x000001, "Wrong size on BP_FriendSearchEntry_C_BP_OnItemExpansionChanged");
static_assert(offsetof(BP_FriendSearchEntry_C_BP_OnItemExpansionChanged, bIsExpanded) == 0x000000, "Member 'BP_FriendSearchEntry_C_BP_OnItemExpansionChanged::bIsExpanded' has a wrong offset!");

// Function BP_FriendSearchEntry.BP_FriendSearchEntry_C.UpdateAvatar
// 0x0060 (0x0060 - 0x0000)
struct BP_FriendSearchEntry_C_UpdateAvatar final
{
public:
	struct FPlayFabPlayer                         Player;                                            // 0x0000(0x0060)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
static_assert(alignof(BP_FriendSearchEntry_C_UpdateAvatar) == 0x000008, "Wrong alignment on BP_FriendSearchEntry_C_UpdateAvatar");
static_assert(sizeof(BP_FriendSearchEntry_C_UpdateAvatar) == 0x000060, "Wrong size on BP_FriendSearchEntry_C_UpdateAvatar");
static_assert(offsetof(BP_FriendSearchEntry_C_UpdateAvatar, Player) == 0x000000, "Member 'BP_FriendSearchEntry_C_UpdateAvatar::Player' has a wrong offset!");

// Function BP_FriendSearchEntry.BP_FriendSearchEntry_C.ShowPlatformIcon
// 0x0001 (0x0001 - 0x0000)
struct BP_FriendSearchEntry_C_ShowPlatformIcon final
{
public:
	EPlatform                                     EPlatform;                                         // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_FriendSearchEntry_C_ShowPlatformIcon) == 0x000001, "Wrong alignment on BP_FriendSearchEntry_C_ShowPlatformIcon");
static_assert(sizeof(BP_FriendSearchEntry_C_ShowPlatformIcon) == 0x000001, "Wrong size on BP_FriendSearchEntry_C_ShowPlatformIcon");
static_assert(offsetof(BP_FriendSearchEntry_C_ShowPlatformIcon, EPlatform) == 0x000000, "Member 'BP_FriendSearchEntry_C_ShowPlatformIcon::EPlatform' has a wrong offset!");

}

