#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Greatsword_Danesword

#include "Basic.hpp"

#include "BP_Greatsword_Danesword_classes.hpp"
#include "BP_Greatsword_Danesword_parameters.hpp"


namespace SDK
{

// Function BP_Greatsword_Danesword.BP_Greatsword_Danesword_C.ExecuteUbergraph_BP_Greatsword_Danesword
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Greatsword_Danesword_C::ExecuteUbergraph_BP_Greatsword_Danesword(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Greatsword_Danesword_C", "ExecuteUbergraph_BP_Greatsword_Danesword");

	Params::BP_Greatsword_Danesword_C_ExecuteUbergraph_BP_Greatsword_Danesword Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Greatsword_Danesword.BP_Greatsword_Danesword_C.ReceiveTick
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Greatsword_Danesword_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Greatsword_Danesword_C", "ReceiveTick");

	Params::BP_Greatsword_Danesword_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Greatsword_Danesword.BP_Greatsword_Danesword_C.ReceiveActorBeginOverlap
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Greatsword_Danesword_C::ReceiveActorBeginOverlap(class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Greatsword_Danesword_C", "ReceiveActorBeginOverlap");

	Params::BP_Greatsword_Danesword_C_ReceiveActorBeginOverlap Parms{};

	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Greatsword_Danesword.BP_Greatsword_Danesword_C.ReceiveBeginPlay
// (BlueprintCallable, BlueprintEvent)

void UBP_Greatsword_Danesword_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Greatsword_Danesword_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

