#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HUDButtonPrompts

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_HUDButtonPrompts.BP_HUDButtonPrompts_C
// 0x00E8 (0x0348 - 0x0260)
class UBP_HUDButtonPrompts_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient, UObjectWrapper)
	class UWidgetAnimation*                       Vanish_Spec_Prompts;                               // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UBP_ButtonPrompt_C*                     BP_ButtonPrompt_PrimarySpecAction;                 // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_ButtonPrompt_C*                     BP_ButtonPrompt_SecondarySpecAction;               // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_ButtonPrompt_C*                     BP_ButtonPrompt_TertiarySpecAction;                // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_ButtonPrompt_C*                     BP_ChangeLoadoutPrompt;                            // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_ButtonPrompt_C*                     BP_ChangeTeamPrompt;                               // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_ButtonPrompt_C*                     BP_CouchPrompt;                                    // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_SpawnInfo_C*                        BP_SpawnInfo;                                      // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_0;                                         // 0x02A8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_1;                                         // 0x02B0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_2;                                         // 0x02B8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_3;                                         // 0x02C0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_5;                                         // 0x02C8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_EquipmentPrompts;                          // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_SpectatorBinds;                            // 0x02D8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_VehiclePrompts;                            // 0x02E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VerticalBox_9;                                     // 0x02E8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VerticalBox_EquipmentPrompts;                      // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VerticalBox_VehiclePrompts;                        // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TArray<class UBP_ButtonPrompt_C*>             ActionPrompts;                                     // 0x0300(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	TArray<class UBP_ButtonPrompt_C*>             VehiclePrompts;                                    // 0x0310(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	TArray<class UBP_ButtonPrompt_C*>             SpectatorActionPrompts;                            // 0x0320(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	class AMordhauEquipment*                      Right_Hand;                                        // 0x0330(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AMordhauEquipment*                      Left_Hand;                                         // 0x0338(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Should_vanish_spec_prompts;                        // 0x0340(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_BP_HUDButtonPrompts(int32 EntryPoint);
	void Vanish();
	void Play_Vanish_Anim();
	void Show_Equipment_Prompts();
	void Hide_Equipment_Prompts();
	void Construct();
	void Add_Prompt(const class FName ActionName, const class FText& DisplayedText);
	void Clear_Equipment_Prompts();
	void Update_Action_Prompts();
	ESlateVisibility Get_Overlay_SpectatorActionPrompts_Visibility_0();
	void Update_Spectator_Prompts(class AMordhauSpectator* MordhauSpectator);
	ESlateVisibility GetVisibility_0();
	ESlateVisibility Get_Overlay_VehiclePrompts_Visibility_0();
	ESlateVisibility Get_Overlay_SpectatorActionPrompts_Visibility_1();
	void Add_Vehicle_Prompt(const class FName ActionName, const class FText& DisplayedText);
	void Clear_Vehicle_Prompts();
	ESlateVisibility Get_BP_ButtonPrompt_PrimarySpecAction_Visibility_0();
	ESlateVisibility GetVisibility_1();
	ESlateVisibility GetVisibility_3();
	ESlateVisibility GetVisibility_4();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_HUDButtonPrompts_C">();
	}
	static class UBP_HUDButtonPrompts_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_HUDButtonPrompts_C>();
	}
};
static_assert(alignof(UBP_HUDButtonPrompts_C) == 0x000008, "Wrong alignment on UBP_HUDButtonPrompts_C");
static_assert(sizeof(UBP_HUDButtonPrompts_C) == 0x000348, "Wrong size on UBP_HUDButtonPrompts_C");
static_assert(offsetof(UBP_HUDButtonPrompts_C, UberGraphFrame) == 0x000260, "Member 'UBP_HUDButtonPrompts_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, Vanish_Spec_Prompts) == 0x000268, "Member 'UBP_HUDButtonPrompts_C::Vanish_Spec_Prompts' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, BP_ButtonPrompt_PrimarySpecAction) == 0x000270, "Member 'UBP_HUDButtonPrompts_C::BP_ButtonPrompt_PrimarySpecAction' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, BP_ButtonPrompt_SecondarySpecAction) == 0x000278, "Member 'UBP_HUDButtonPrompts_C::BP_ButtonPrompt_SecondarySpecAction' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, BP_ButtonPrompt_TertiarySpecAction) == 0x000280, "Member 'UBP_HUDButtonPrompts_C::BP_ButtonPrompt_TertiarySpecAction' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, BP_ChangeLoadoutPrompt) == 0x000288, "Member 'UBP_HUDButtonPrompts_C::BP_ChangeLoadoutPrompt' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, BP_ChangeTeamPrompt) == 0x000290, "Member 'UBP_HUDButtonPrompts_C::BP_ChangeTeamPrompt' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, BP_CouchPrompt) == 0x000298, "Member 'UBP_HUDButtonPrompts_C::BP_CouchPrompt' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, BP_SpawnInfo) == 0x0002A0, "Member 'UBP_HUDButtonPrompts_C::BP_SpawnInfo' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, Overlay_0) == 0x0002A8, "Member 'UBP_HUDButtonPrompts_C::Overlay_0' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, Overlay_1) == 0x0002B0, "Member 'UBP_HUDButtonPrompts_C::Overlay_1' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, Overlay_2) == 0x0002B8, "Member 'UBP_HUDButtonPrompts_C::Overlay_2' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, Overlay_3) == 0x0002C0, "Member 'UBP_HUDButtonPrompts_C::Overlay_3' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, Overlay_5) == 0x0002C8, "Member 'UBP_HUDButtonPrompts_C::Overlay_5' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, Overlay_EquipmentPrompts) == 0x0002D0, "Member 'UBP_HUDButtonPrompts_C::Overlay_EquipmentPrompts' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, Overlay_SpectatorBinds) == 0x0002D8, "Member 'UBP_HUDButtonPrompts_C::Overlay_SpectatorBinds' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, Overlay_VehiclePrompts) == 0x0002E0, "Member 'UBP_HUDButtonPrompts_C::Overlay_VehiclePrompts' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, VerticalBox_9) == 0x0002E8, "Member 'UBP_HUDButtonPrompts_C::VerticalBox_9' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, VerticalBox_EquipmentPrompts) == 0x0002F0, "Member 'UBP_HUDButtonPrompts_C::VerticalBox_EquipmentPrompts' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, VerticalBox_VehiclePrompts) == 0x0002F8, "Member 'UBP_HUDButtonPrompts_C::VerticalBox_VehiclePrompts' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, ActionPrompts) == 0x000300, "Member 'UBP_HUDButtonPrompts_C::ActionPrompts' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, VehiclePrompts) == 0x000310, "Member 'UBP_HUDButtonPrompts_C::VehiclePrompts' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, SpectatorActionPrompts) == 0x000320, "Member 'UBP_HUDButtonPrompts_C::SpectatorActionPrompts' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, Right_Hand) == 0x000330, "Member 'UBP_HUDButtonPrompts_C::Right_Hand' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, Left_Hand) == 0x000338, "Member 'UBP_HUDButtonPrompts_C::Left_Hand' has a wrong offset!");
static_assert(offsetof(UBP_HUDButtonPrompts_C, Should_vanish_spec_prompts) == 0x000340, "Member 'UBP_HUDButtonPrompts_C::Should_vanish_spec_prompts' has a wrong offset!");

}

