#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HordeRespawnTimer

#include "Basic.hpp"

#include "BP_HordeRespawnTimer_classes.hpp"
#include "BP_HordeRespawnTimer_parameters.hpp"


namespace SDK
{

// Function BP_HordeRespawnTimer.BP_HordeRespawnTimer_C.ExecuteUbergraph_BP_HordeRespawnTimer
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_HordeRespawnTimer_C::ExecuteUbergraph_BP_HordeRespawnTimer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HordeRespawnTimer_C", "ExecuteUbergraph_BP_HordeRespawnTimer");

	Params::BP_HordeRespawnTimer_C_ExecuteUbergraph_BP_HordeRespawnTimer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HordeRespawnTimer.BP_HordeRespawnTimer_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_HordeRespawnTimer_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HordeRespawnTimer_C", "Tick");

	Params::BP_HordeRespawnTimer_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HordeRespawnTimer.BP_HordeRespawnTimer_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_HordeRespawnTimer_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HordeRespawnTimer_C", "PreConstruct");

	Params::BP_HordeRespawnTimer_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HordeRespawnTimer.BP_HordeRespawnTimer_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_HordeRespawnTimer_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HordeRespawnTimer_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_HordeRespawnTimer.BP_HordeRespawnTimer_C.Initialize
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Respawn_Time                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_HordeRespawnTimer_C::Initialize(float Respawn_Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HordeRespawnTimer_C", "Initialize");

	Params::BP_HordeRespawnTimer_C_Initialize Parms{};

	Parms.Respawn_Time = Respawn_Time;

	UObject::ProcessEvent(Func, &Parms);
}

}

