#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Hoe

#include "Basic.hpp"

#include "BP_Halberd_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Hoe.BP_Hoe_C
// 0x0000 (0x1CA0 - 0x1CA0)
#pragma pack(push, 0x1)
class alignas(0x10) ABP_Hoe_C : public ABP_Halberd_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Hoe_C">();
	}
	static class ABP_Hoe_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Hoe_C>();
	}
};
#pragma pack(pop)
static_assert(alignof(ABP_Hoe_C) == 0x000010, "Wrong alignment on ABP_Hoe_C");
static_assert(sizeof(ABP_Hoe_C) == 0x001CA0, "Wrong size on ABP_Hoe_C");

}

