#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_InGoreMeshBlunt

#include "Basic.hpp"

#include "BP_BaseGoreMesh_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_InGoreMeshBlunt.BP_InGoreMeshBlunt_C
// 0x0000 (0x0240 - 0x0240)
class ABP_InGoreMeshBlunt_C : public ABP_BaseGoreMesh_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_InGoreMeshBlunt_C">();
	}
	static class ABP_InGoreMeshBlunt_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_InGoreMeshBlunt_C>();
	}
};
static_assert(alignof(ABP_InGoreMeshBlunt_C) == 0x000008, "Wrong alignment on ABP_InGoreMeshBlunt_C");
static_assert(sizeof(ABP_InGoreMeshBlunt_C) == 0x000240, "Wrong size on ABP_InGoreMeshBlunt_C");

}

