#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ItsAllOver

#include "Basic.hpp"

#include "Mordhau_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ItsAllOver.BP_ItsAllOver_C
// 0x0000 (0x0130 - 0x0130)
class UBP_ItsAllOver_C final : public UEmoteMotion
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ItsAllOver_C">();
	}
	static class UBP_ItsAllOver_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ItsAllOver_C>();
	}
};
static_assert(alignof(UBP_ItsAllOver_C) == 0x000008, "Wrong alignment on UBP_ItsAllOver_C");
static_assert(sizeof(UBP_ItsAllOver_C) == 0x000130, "Wrong size on UBP_ItsAllOver_C");

}

