#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Ladder1H_LeftStabMotion

#include "Basic.hpp"

#include "BP_LeftStabMotion_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Ladder1H_LeftStabMotion.BP_Ladder1H_LeftStabMotion_C
// 0x0000 (0x1118 - 0x1118)
class UBP_Ladder1H_LeftStabMotion_C final : public UBP_LeftStabMotion_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Ladder1H_LeftStabMotion_C">();
	}
	static class UBP_Ladder1H_LeftStabMotion_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Ladder1H_LeftStabMotion_C>();
	}
};
static_assert(alignof(UBP_Ladder1H_LeftStabMotion_C) == 0x000008, "Wrong alignment on UBP_Ladder1H_LeftStabMotion_C");
static_assert(sizeof(UBP_Ladder1H_LeftStabMotion_C) == 0x001118, "Wrong size on UBP_Ladder1H_LeftStabMotion_C");

}

