#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LongGroomedMale01

#include "Basic.hpp"

#include "Mordhau_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_LongGroomedMale01.BP_LongGroomedMale01_C
// 0x0000 (0x00A0 - 0x00A0)
class UBP_LongGroomedMale01_C final : public UCharacterHair
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_LongGroomedMale01_C">();
	}
	static class UBP_LongGroomedMale01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_LongGroomedMale01_C>();
	}
};
static_assert(alignof(UBP_LongGroomedMale01_C) == 0x000008, "Wrong alignment on UBP_LongGroomedMale01_C");
static_assert(sizeof(UBP_LongGroomedMale01_C) == 0x0000A0, "Wrong size on UBP_LongGroomedMale01_C");

}

