#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LongBackSweptFemale01

#include "Basic.hpp"

#include "Mordhau_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_LongBackSweptFemale01.BP_LongBackSweptFemale01_C
// 0x0000 (0x00A0 - 0x00A0)
class UBP_LongBackSweptFemale01_C final : public UCharacterHair
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_LongBackSweptFemale01_C">();
	}
	static class UBP_LongBackSweptFemale01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_LongBackSweptFemale01_C>();
	}
};
static_assert(alignof(UBP_LongBackSweptFemale01_C) == 0x000008, "Wrong alignment on UBP_LongBackSweptFemale01_C");
static_assert(sizeof(UBP_LongBackSweptFemale01_C) == 0x0000A0, "Wrong size on UBP_LongBackSweptFemale01_C");

}

