#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MonkCutMale02

#include "Basic.hpp"

#include "Mordhau_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MonkCutMale02.BP_MonkCutMale02_C
// 0x0000 (0x00A0 - 0x00A0)
class UBP_MonkCutMale02_C final : public UCharacterHair
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MonkCutMale02_C">();
	}
	static class UBP_MonkCutMale02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MonkCutMale02_C>();
	}
};
static_assert(alignof(UBP_MonkCutMale02_C) == 0x000008, "Wrong alignment on UBP_MonkCutMale02_C");
static_assert(sizeof(UBP_MonkCutMale02_C) == 0x0000A0, "Wrong size on UBP_MonkCutMale02_C");

}

