#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MaulGradCommander

#include "Basic.hpp"

#include "BP_Maul_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MaulGradCommander.BP_MaulGradCommander_C
// 0x0000 (0x1CA0 - 0x1CA0)
class ABP_MaulGradCommander_C final : public ABP_Maul_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MaulGradCommander_C">();
	}
	static class ABP_MaulGradCommander_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MaulGradCommander_C>();
	}
};
static_assert(alignof(ABP_MaulGradCommander_C) == 0x000010, "Wrong alignment on ABP_MaulGradCommander_C");
static_assert(sizeof(ABP_MaulGradCommander_C) == 0x001CA0, "Wrong size on ABP_MaulGradCommander_C");

}

