#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MailleHoodLoweredCoif

#include "Basic.hpp"

#include "BP_MordhauWearable_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MailleHoodLoweredCoif.BP_MailleHoodLoweredCoif_C
// 0x0000 (0x0228 - 0x0228)
class UBP_MailleHoodLoweredCoif_C final : public UBP_MordhauWearable_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MailleHoodLoweredCoif_C">();
	}
	static class UBP_MailleHoodLoweredCoif_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MailleHoodLoweredCoif_C>();
	}
};
static_assert(alignof(UBP_MailleHoodLoweredCoif_C) == 0x000008, "Wrong alignment on UBP_MailleHoodLoweredCoif_C");
static_assert(sizeof(UBP_MailleHoodLoweredCoif_C) == 0x000228, "Wrong size on UBP_MailleHoodLoweredCoif_C");

}

