#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MatchmakingSearchWidget

#include "Basic.hpp"

#include "BP_MatchmakingSearchWidget_classes.hpp"
#include "BP_MatchmakingSearchWidget_parameters.hpp"


namespace SDK
{

// Function BP_MatchmakingSearchWidget.BP_MatchmakingSearchWidget_C.ExecuteUbergraph_BP_MatchmakingSearchWidget
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_MatchmakingSearchWidget_C::ExecuteUbergraph_BP_MatchmakingSearchWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MatchmakingSearchWidget_C", "ExecuteUbergraph_BP_MatchmakingSearchWidget");

	Params::BP_MatchmakingSearchWidget_C_ExecuteUbergraph_BP_MatchmakingSearchWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MatchmakingSearchWidget.BP_MatchmakingSearchWidget_C.Deactivate
// (BlueprintCallable, BlueprintEvent)

void UBP_MatchmakingSearchWidget_C::Deactivate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MatchmakingSearchWidget_C", "Deactivate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MatchmakingSearchWidget.BP_MatchmakingSearchWidget_C.Activate
// (BlueprintCallable, BlueprintEvent)

void UBP_MatchmakingSearchWidget_C::Activate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MatchmakingSearchWidget_C", "Activate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MatchmakingSearchWidget.BP_MatchmakingSearchWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_MatchmakingSearchWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MatchmakingSearchWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MatchmakingSearchWidget.BP_MatchmakingSearchWidget_C.Get_TextBlock_Text_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText UBP_MatchmakingSearchWidget_C::Get_TextBlock_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MatchmakingSearchWidget_C", "Get_TextBlock_Text_0");

	Params::BP_MatchmakingSearchWidget_C_Get_TextBlock_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

