#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MaleFaceBlack01

#include "Basic.hpp"

#include "Mordhau_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MaleFaceBlack01.BP_MaleFaceBlack01_C
// 0x0000 (0x04D8 - 0x04D8)
class UBP_MaleFaceBlack01_C final : public UCharacterFace
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MaleFaceBlack01_C">();
	}
	static class UBP_MaleFaceBlack01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MaleFaceBlack01_C>();
	}
};
static_assert(alignof(UBP_MaleFaceBlack01_C) == 0x000008, "Wrong alignment on UBP_MaleFaceBlack01_C");
static_assert(sizeof(UBP_MaleFaceBlack01_C) == 0x0004D8, "Wrong size on UBP_MaleFaceBlack01_C");

}

