#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_OutGoreMeshBlunt_Corpse

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_BaseGoreMesh_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_OutGoreMeshBlunt_Corpse.BP_OutGoreMeshBlunt_Corpse_C
// 0x0008 (0x0248 - 0x0240)
class ABP_OutGoreMeshBlunt_Corpse_C final : public ABP_BaseGoreMesh_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_OutGoreMeshBlunt_Corpse_C;       // 0x0240(0x0008)(ZeroConstructor, Transient, DuplicateTransient, UObjectWrapper)

public:
	void ExecuteUbergraph_BP_OutGoreMeshBlunt_Corpse(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_OutGoreMeshBlunt_Corpse_C">();
	}
	static class ABP_OutGoreMeshBlunt_Corpse_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_OutGoreMeshBlunt_Corpse_C>();
	}
};
static_assert(alignof(ABP_OutGoreMeshBlunt_Corpse_C) == 0x000008, "Wrong alignment on ABP_OutGoreMeshBlunt_Corpse_C");
static_assert(sizeof(ABP_OutGoreMeshBlunt_Corpse_C) == 0x000248, "Wrong size on ABP_OutGoreMeshBlunt_Corpse_C");
static_assert(offsetof(ABP_OutGoreMeshBlunt_Corpse_C, UberGraphFrame_BP_OutGoreMeshBlunt_Corpse_C) == 0x000240, "Member 'ABP_OutGoreMeshBlunt_Corpse_C::UberGraphFrame_BP_OutGoreMeshBlunt_Corpse_C' has a wrong offset!");

}

