#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PassiveSkillPopupEntry

#include "Basic.hpp"

#include "BP_PassiveSkillPopupEntry_classes.hpp"
#include "BP_PassiveSkillPopupEntry_parameters.hpp"


namespace SDK
{

// Function BP_PassiveSkillPopupEntry.BP_PassiveSkillPopupEntry_C.Initialize
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             InText                                                 (BlueprintVisible, BlueprintReadOnly, Parm)
// class UTexture2D*                       Texture                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_PassiveSkillPopupEntry_C::Initialize(const class FText& InText, class UTexture2D* Texture)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PassiveSkillPopupEntry_C", "Initialize");

	Params::BP_PassiveSkillPopupEntry_C_Initialize Parms{};

	Parms.InText = std::move(InText);
	Parms.Texture = Texture;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PassiveSkillPopupEntry.BP_PassiveSkillPopupEntry_C.BP_PassiveSkillPopupEntry_OnAnimFinish
// (Public, BlueprintCallable, BlueprintEvent)

void UBP_PassiveSkillPopupEntry_C::BP_PassiveSkillPopupEntry_OnAnimFinish()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PassiveSkillPopupEntry_C", "BP_PassiveSkillPopupEntry_OnAnimFinish");

	UObject::ProcessEvent(Func, nullptr);
}

}

