#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ProfileSelectButton

#include "Basic.hpp"

#include "BP_ProfileSelectButton_classes.hpp"
#include "BP_ProfileSelectButton_parameters.hpp"


namespace SDK
{

// Function BP_ProfileSelectButton.BP_ProfileSelectButton_C.ExecuteUbergraph_BP_ProfileSelectButton
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ProfileSelectButton_C::ExecuteUbergraph_BP_ProfileSelectButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ProfileSelectButton_C", "ExecuteUbergraph_BP_ProfileSelectButton");

	Params::BP_ProfileSelectButton_C_ExecuteUbergraph_BP_ProfileSelectButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ProfileSelectButton.BP_ProfileSelectButton_C.BndEvt__Button_1_K2Node_ComponentBoundEvent_380_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UBP_ProfileSelectButton_C::BndEvt__Button_1_K2Node_ComponentBoundEvent_380_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ProfileSelectButton_C", "BndEvt__Button_1_K2Node_ComponentBoundEvent_380_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ProfileSelectButton.BP_ProfileSelectButton_C.BndEvt__Button_1_K2Node_ComponentBoundEvent_369_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UBP_ProfileSelectButton_C::BndEvt__Button_1_K2Node_ComponentBoundEvent_369_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ProfileSelectButton_C", "BndEvt__Button_1_K2Node_ComponentBoundEvent_369_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ProfileSelectButton.BP_ProfileSelectButton_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_ProfileSelectButton_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ProfileSelectButton_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ProfileSelectButton.BP_ProfileSelectButton_C.BndEvt__Button_1_K2Node_ComponentBoundEvent_46_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBP_ProfileSelectButton_C::BndEvt__Button_1_K2Node_ComponentBoundEvent_46_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ProfileSelectButton_C", "BndEvt__Button_1_K2Node_ComponentBoundEvent_46_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}

}

