#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlayerAvatar

#include "Basic.hpp"

#include "BP_PlayerAvatar_classes.hpp"
#include "BP_PlayerAvatar_parameters.hpp"


namespace SDK
{

// Function BP_PlayerAvatar.BP_PlayerAvatar_C.ExecuteUbergraph_BP_PlayerAvatar
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_PlayerAvatar_C::ExecuteUbergraph_BP_PlayerAvatar(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerAvatar_C", "ExecuteUbergraph_BP_PlayerAvatar");

	Params::BP_PlayerAvatar_C_ExecuteUbergraph_BP_PlayerAvatar Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PlayerAvatar.BP_PlayerAvatar_C.OnPlayerInformationReceived
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPlayFabPlayer                   Player_0                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)

void UBP_PlayerAvatar_C::OnPlayerInformationReceived(const struct FPlayFabPlayer& Player_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerAvatar_C", "OnPlayerInformationReceived");

	Params::BP_PlayerAvatar_C_OnPlayerInformationReceived Parms{};

	Parms.Player_0 = std::move(Player_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PlayerAvatar.BP_PlayerAvatar_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_PlayerAvatar_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerAvatar_C", "PreConstruct");

	Params::BP_PlayerAvatar_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PlayerAvatar.BP_PlayerAvatar_C.Update
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPlayFabPlayer                   Player_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UBP_PlayerAvatar_C::Update(const struct FPlayFabPlayer& Player_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerAvatar_C", "Update");

	Params::BP_PlayerAvatar_C_Update Parms{};

	Parms.Player_0 = std::move(Player_0);

	UObject::ProcessEvent(Func, &Parms);
}

}

