#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Rapier_SmallcupGuard

#include "Basic.hpp"

#include "BP_MordhauEquipmentPart_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Rapier_SmallcupGuard.BP_Rapier_SmallcupGuard_C
// 0x0008 (0x0090 - 0x0088)
class UBP_Rapier_SmallcupGuard_C final : public UBP_MordhauEquipmentPart_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0088(0x0008)(ZeroConstructor, Transient, DuplicateTransient, UObjectWrapper)

public:
	void ExecuteUbergraph_BP_Rapier_SmallcupGuard(int32 EntryPoint);
	void ReceiveTick(float DeltaSeconds);
	void ReceiveActorBeginOverlap(class AActor* OtherActor);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Rapier_SmallcupGuard_C">();
	}
	static class UBP_Rapier_SmallcupGuard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Rapier_SmallcupGuard_C>();
	}
};
static_assert(alignof(UBP_Rapier_SmallcupGuard_C) == 0x000008, "Wrong alignment on UBP_Rapier_SmallcupGuard_C");
static_assert(sizeof(UBP_Rapier_SmallcupGuard_C) == 0x000090, "Wrong size on UBP_Rapier_SmallcupGuard_C");
static_assert(offsetof(UBP_Rapier_SmallcupGuard_C, UberGraphFrame) == 0x000088, "Member 'UBP_Rapier_SmallcupGuard_C::UberGraphFrame' has a wrong offset!");

}

