#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RadialGradient

#include "Basic.hpp"

#include "BP_RadialGradient_classes.hpp"
#include "BP_RadialGradient_parameters.hpp"


namespace SDK
{

// Function BP_RadialGradient.BP_RadialGradient_C.ExecuteUbergraph_BP_RadialGradient
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_RadialGradient_C::ExecuteUbergraph_BP_RadialGradient(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RadialGradient_C", "ExecuteUbergraph_BP_RadialGradient");

	Params::BP_RadialGradient_C_ExecuteUbergraph_BP_RadialGradient Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_RadialGradient.BP_RadialGradient_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_RadialGradient_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RadialGradient_C", "PreConstruct");

	Params::BP_RadialGradient_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_RadialGradient.BP_RadialGradient_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_RadialGradient_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RadialGradient_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

