#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SeparatedBodyPart_Corpse

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Mordhau_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_SeparatedBodyPart_Corpse.BP_SeparatedBodyPart_Corpse_C.ExecuteUbergraph_BP_SeparatedBodyPart_Corpse
// 0x0320 (0x0320 - 0x0000)
struct BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMordhauGameUserSettings*               CallFunc_GetMordhauGameUserSettings_ReturnValue;   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_ShouldShowBlood_ReturnValue;              // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_RandomIntegerInRange_ReturnValue;         // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_RandomIntegerInRange_ReturnValue_1;       // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue_1;            // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<EObjectTypeQuery>                      K2Node_MakeArray_Array;                            // 0x0028(0x0010)(ConstParm, ReferenceParm)
	EMordhauDamageType                            K2Node_Event_DamageType;                           // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         K2Node_Event_SubType;                              // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A[0x2];                                       // 0x003A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             K2Node_Event_Hit;                                  // 0x003C(0x008C)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class AActor*                                 K2Node_Event_Agent;                                // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetSocketLocation_ReturnValue;            // 0x00D0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x00DC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x00E9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_EA[0x2];                                       // 0x00EA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x00EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x00F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x00F4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x0100(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x010C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x0118(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_124[0x4];                                      // 0x0124(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x0128(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x0130(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x0138(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x0140(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x0148(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x014C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x0150(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x015C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         Temp_object_Variable;                              // 0x0168(0x0010)(ConstParm, ReferenceParm)
	struct FHitResult                             CallFunc_LineTraceSingleForObjects_OutHit;         // 0x0178(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_LineTraceSingleForObjects_ReturnValue;    // 0x0204(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bBlockingHit_1;            // 0x0205(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap_1;         // 0x0206(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_207[0x1];                                      // 0x0207(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time_1;                    // 0x0208(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance_1;                // 0x020C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location_1;                // 0x0210(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint_1;             // 0x021C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal_1;                  // 0x0228(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal_1;            // 0x0234(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat_1;                 // 0x0240(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor_1;                // 0x0248(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent_1;            // 0x0250(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName_1;             // 0x0258(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem_1;                 // 0x0260(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex_1;               // 0x0264(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart_1;              // 0x0268(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd_1;                // 0x0274(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue;         // 0x0280(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotFromX_ReturnValue;                 // 0x028C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UDecalComponent*                        CallFunc_SpawnBloodDecalAtLocation_ReturnValue;    // 0x0298(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_FloatFloat_ReturnValue;              // 0x02A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x02A1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2A2[0x6];                                      // 0x02A2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x02A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x02B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_MapRangeClamped_ReturnValue;              // 0x02B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        CallFunc_SpawnSoundAttached_ReturnValue;           // 0x02B8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AMordhauCharacter*                      K2Node_Event_Source;                               // 0x02C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_Event_Bone;                                 // 0x02C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             K2Node_Event_SourceBoneTransform;                  // 0x02D0(0x0030)(IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bIsPartial;                           // 0x0300(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bIsBluntForce;                        // 0x0301(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_302[0x2];                                      // 0x0302(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetRealTimeSeconds_ReturnValue;           // 0x0304(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_ComputeRagdollForce_Force;                // 0x0308(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue_1;       // 0x0314(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse) == 0x000010, "Wrong alignment on BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse");
static_assert(sizeof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse) == 0x000320, "Wrong size on BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, EntryPoint) == 0x000000, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_GetMordhauGameUserSettings_ReturnValue) == 0x000008, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_GetMordhauGameUserSettings_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_ShouldShowBlood_ReturnValue) == 0x000010, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_ShouldShowBlood_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_RandomIntegerInRange_ReturnValue) == 0x000014, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_RandomIntegerInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_RandomIntegerInRange_ReturnValue_1) == 0x000018, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_RandomIntegerInRange_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_Conv_IntToFloat_ReturnValue) == 0x00001C, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_Conv_IntToFloat_ReturnValue_1) == 0x000020, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_Conv_IntToFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, K2Node_MakeArray_Array) == 0x000028, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, K2Node_Event_DamageType) == 0x000038, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::K2Node_Event_DamageType' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, K2Node_Event_SubType) == 0x000039, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::K2Node_Event_SubType' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, K2Node_Event_Hit) == 0x00003C, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::K2Node_Event_Hit' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, K2Node_Event_Agent) == 0x0000C8, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::K2Node_Event_Agent' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_GetSocketLocation_ReturnValue) == 0x0000D0, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_GetSocketLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_Add_VectorVector_ReturnValue) == 0x0000DC, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_bBlockingHit) == 0x0000E8, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_bInitialOverlap) == 0x0000E9, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_Time) == 0x0000EC, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_Distance) == 0x0000F0, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_Location) == 0x0000F4, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_ImpactPoint) == 0x000100, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_Normal) == 0x00010C, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_ImpactNormal) == 0x000118, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_PhysMat) == 0x000128, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_HitActor) == 0x000130, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_HitComponent) == 0x000138, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_HitBoneName) == 0x000140, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_HitItem) == 0x000148, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_FaceIndex) == 0x00014C, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_TraceStart) == 0x000150, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_TraceEnd) == 0x00015C, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, Temp_object_Variable) == 0x000168, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_LineTraceSingleForObjects_OutHit) == 0x000178, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_LineTraceSingleForObjects_OutHit' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_LineTraceSingleForObjects_ReturnValue) == 0x000204, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_LineTraceSingleForObjects_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_bBlockingHit_1) == 0x000205, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_bBlockingHit_1' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_bInitialOverlap_1) == 0x000206, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_bInitialOverlap_1' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_Time_1) == 0x000208, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_Time_1' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_Distance_1) == 0x00020C, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_Distance_1' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_Location_1) == 0x000210, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_Location_1' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_ImpactPoint_1) == 0x00021C, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_ImpactPoint_1' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_Normal_1) == 0x000228, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_Normal_1' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_ImpactNormal_1) == 0x000234, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_ImpactNormal_1' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_PhysMat_1) == 0x000240, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_PhysMat_1' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_HitActor_1) == 0x000248, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_HitActor_1' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_HitComponent_1) == 0x000250, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_HitComponent_1' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_HitBoneName_1) == 0x000258, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_HitBoneName_1' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_HitItem_1) == 0x000260, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_HitItem_1' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_FaceIndex_1) == 0x000264, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_FaceIndex_1' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_TraceStart_1) == 0x000268, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_TraceStart_1' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_BreakHitResult_TraceEnd_1) == 0x000274, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_BreakHitResult_TraceEnd_1' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_Multiply_VectorFloat_ReturnValue) == 0x000280, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_Multiply_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_MakeRotFromX_ReturnValue) == 0x00028C, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_MakeRotFromX_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_SpawnBloodDecalAtLocation_ReturnValue) == 0x000298, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_SpawnBloodDecalAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_Less_FloatFloat_ReturnValue) == 0x0002A0, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_Less_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_IsValid_ReturnValue) == 0x0002A1, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_CreateDynamicMaterialInstance_ReturnValue) == 0x0002A8, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_CreateDynamicMaterialInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x0002B0, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_MapRangeClamped_ReturnValue) == 0x0002B4, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_MapRangeClamped_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_SpawnSoundAttached_ReturnValue) == 0x0002B8, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_SpawnSoundAttached_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, K2Node_Event_Source) == 0x0002C0, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::K2Node_Event_Source' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, K2Node_Event_Bone) == 0x0002C8, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::K2Node_Event_Bone' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, K2Node_Event_SourceBoneTransform) == 0x0002D0, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::K2Node_Event_SourceBoneTransform' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, K2Node_Event_bIsPartial) == 0x000300, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::K2Node_Event_bIsPartial' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, K2Node_Event_bIsBluntForce) == 0x000301, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::K2Node_Event_bIsBluntForce' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_GetRealTimeSeconds_ReturnValue) == 0x000304, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_GetRealTimeSeconds_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_ComputeRagdollForce_Force) == 0x000308, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_ComputeRagdollForce_Force' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse, CallFunc_Multiply_VectorFloat_ReturnValue_1) == 0x000314, "Member 'BP_SeparatedBodyPart_Corpse_C_ExecuteUbergraph_BP_SeparatedBodyPart_Corpse::CallFunc_Multiply_VectorFloat_ReturnValue_1' has a wrong offset!");

// Function BP_SeparatedBodyPart_Corpse.BP_SeparatedBodyPart_Corpse_C.InitializeDismemberment
// 0x0050 (0x0050 - 0x0000)
struct BP_SeparatedBodyPart_Corpse_C_InitializeDismemberment final
{
public:
	class AMordhauCharacter*                      Source;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   bone;                                              // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             SourceBoneTransform;                               // 0x0010(0x0030)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	bool                                          bIsPartial;                                        // 0x0040(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          bIsBluntForce;                                     // 0x0041(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_SeparatedBodyPart_Corpse_C_InitializeDismemberment) == 0x000010, "Wrong alignment on BP_SeparatedBodyPart_Corpse_C_InitializeDismemberment");
static_assert(sizeof(BP_SeparatedBodyPart_Corpse_C_InitializeDismemberment) == 0x000050, "Wrong size on BP_SeparatedBodyPart_Corpse_C_InitializeDismemberment");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_InitializeDismemberment, Source) == 0x000000, "Member 'BP_SeparatedBodyPart_Corpse_C_InitializeDismemberment::Source' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_InitializeDismemberment, bone) == 0x000008, "Member 'BP_SeparatedBodyPart_Corpse_C_InitializeDismemberment::bone' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_InitializeDismemberment, SourceBoneTransform) == 0x000010, "Member 'BP_SeparatedBodyPart_Corpse_C_InitializeDismemberment::SourceBoneTransform' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_InitializeDismemberment, bIsPartial) == 0x000040, "Member 'BP_SeparatedBodyPart_Corpse_C_InitializeDismemberment::bIsPartial' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_InitializeDismemberment, bIsBluntForce) == 0x000041, "Member 'BP_SeparatedBodyPart_Corpse_C_InitializeDismemberment::bIsBluntForce' has a wrong offset!");

// Function BP_SeparatedBodyPart_Corpse.BP_SeparatedBodyPart_Corpse_C.OnCosmeticHit
// 0x0098 (0x0098 - 0x0000)
struct BP_SeparatedBodyPart_Corpse_C_OnCosmeticHit final
{
public:
	EMordhauDamageType                            DamageType;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         SubType;                                           // 0x0001(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2[0x2];                                        // 0x0002(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             Hit;                                               // 0x0004(0x008C)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	class AActor*                                 Agent;                                             // 0x0090(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SeparatedBodyPart_Corpse_C_OnCosmeticHit) == 0x000008, "Wrong alignment on BP_SeparatedBodyPart_Corpse_C_OnCosmeticHit");
static_assert(sizeof(BP_SeparatedBodyPart_Corpse_C_OnCosmeticHit) == 0x000098, "Wrong size on BP_SeparatedBodyPart_Corpse_C_OnCosmeticHit");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_OnCosmeticHit, DamageType) == 0x000000, "Member 'BP_SeparatedBodyPart_Corpse_C_OnCosmeticHit::DamageType' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_OnCosmeticHit, SubType) == 0x000001, "Member 'BP_SeparatedBodyPart_Corpse_C_OnCosmeticHit::SubType' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_OnCosmeticHit, Hit) == 0x000004, "Member 'BP_SeparatedBodyPart_Corpse_C_OnCosmeticHit::Hit' has a wrong offset!");
static_assert(offsetof(BP_SeparatedBodyPart_Corpse_C_OnCosmeticHit, Agent) == 0x000090, "Member 'BP_SeparatedBodyPart_Corpse_C_OnCosmeticHit::Agent' has a wrong offset!");

}

