#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Shortspear

#include "Basic.hpp"

#include "BP_OneHandedSword_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Shortspear.BP_Shortspear_C
// 0x0000 (0x1CA0 - 0x1CA0)
#pragma pack(push, 0x1)
class alignas(0x10) ABP_Shortspear_C : public ABP_OneHandedSword_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Shortspear_C">();
	}
	static class ABP_Shortspear_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Shortspear_C>();
	}
};
#pragma pack(pop)
static_assert(alignof(ABP_Shortspear_C) == 0x000010, "Wrong alignment on ABP_Shortspear_C");
static_assert(sizeof(ABP_Shortspear_C) == 0x001CA0, "Wrong size on ABP_Shortspear_C");

}

