#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Stick_DIH

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_Stick_classes.hpp"
#include "Mordhau_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Stick_DIH.BP_Stick_DIH_C
// 0x0010 (0x1CB0 - 0x1CA0)
class ABP_Stick_DIH_C final : public ABP_Stick_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x1C98(0x0008)(ZeroConstructor, Transient, DuplicateTransient, UObjectWrapper)
	class ABP_DemonHordeCharacter_C*              OwningCharacter;                                   // 0x1CA0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Stick_DIH(int32 EntryPoint);
	void SetupBlessingStats();
	void ImpactSoundMulti();
	void CreateAndFireProjectile(float Accuracy, class UClass* Projectile);
	void MeleeRelease(EAttackMove Direction, float Angle, EAttackType Type);
	void OnEquipped(class AMordhauCharacter* Character);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Stick_DIH_C">();
	}
	static class ABP_Stick_DIH_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Stick_DIH_C>();
	}
};
static_assert(alignof(ABP_Stick_DIH_C) == 0x000010, "Wrong alignment on ABP_Stick_DIH_C");
static_assert(sizeof(ABP_Stick_DIH_C) == 0x001CB0, "Wrong size on ABP_Stick_DIH_C");
static_assert(offsetof(ABP_Stick_DIH_C, UberGraphFrame) == 0x001C98, "Member 'ABP_Stick_DIH_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_Stick_DIH_C, OwningCharacter) == 0x001CA0, "Member 'ABP_Stick_DIH_C::OwningCharacter' has a wrong offset!");

}

