#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SmokeField

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function BP_SmokeField.BP_SmokeField_C.ExecuteUbergraph_BP_SmokeField
// 0x00E8 (0x00E8 - 0x0000)
struct BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         CallFunc_Map_Keys_Keys;                            // 0x0010(0x0010)(ReferenceParm)
	class AActor*                                 CallFunc_Array_Get_Item;                           // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_SmokeSubField_C*                    K2Node_DynamicCast_AsBP_Smoke_Sub_Field;           // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Map_Find_Value;                           // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_42[0x6];                                       // 0x0042(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AMasterField*                           CallFunc_GetMaster_ReturnValue;                    // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0050(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AAdvancedCharacter*                     K2Node_DynamicCast_AsAdvanced_Character;           // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_69[0x3];                                       // 0x0069(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_ComputeDistanceIntoField_ReturnValue;     // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue;      // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue_1;    // 0x0071(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_72[0x6];                                       // 0x0072(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_FireSubField_C*                     K2Node_DynamicCast_AsBP_Fire_Sub_Field;            // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AMasterField*                           CallFunc_GetMaster_ReturnValue_1;                  // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x0090(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_ComputeDistanceIntoField_ReturnValue_1;   // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue_2;    // 0x00A4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00A5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A6[0x2];                                       // 0x00A6(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_AC[0x4];                                       // 0x00AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AMordhauCharacter*                      CallFunc_GetViewTargetCharacter_ReturnValue;       // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C1[0x7];                                       // 0x00C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_MordhauPlayerController_C*          K2Node_DynamicCast_AsBP_Mordhau_Player_Controller; // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x00D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsLocalPlayerController_ReturnValue;      // 0x00D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_FloatFloat_ReturnValue;        // 0x00D2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x00D3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue;         // 0x00D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00D5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D6[0x2];                                       // 0x00D6(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Add_FloatFloat_ReturnValue;               // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetTimeSeconds_ReturnValue;               // 0x00DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue_1;       // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField) == 0x000008, "Wrong alignment on BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField");
static_assert(sizeof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField) == 0x0000E8, "Wrong size on BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, EntryPoint) == 0x000000, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, Temp_int_Array_Index_Variable) == 0x000004, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, K2Node_Event_DeltaSeconds) == 0x000008, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_Map_Keys_Keys) == 0x000010, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_Map_Keys_Keys' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_Array_Get_Item) == 0x000020, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_Array_Length_ReturnValue) == 0x000028, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, K2Node_DynamicCast_AsBP_Smoke_Sub_Field) == 0x000030, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::K2Node_DynamicCast_AsBP_Smoke_Sub_Field' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, K2Node_DynamicCast_bSuccess) == 0x000038, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_Map_Find_Value) == 0x00003C, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_Map_Find_Value' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_Map_Find_ReturnValue) == 0x000040, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_Map_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x000041, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_GetMaster_ReturnValue) == 0x000048, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_GetMaster_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000050, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, K2Node_DynamicCast_AsAdvanced_Character) == 0x000060, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::K2Node_DynamicCast_AsAdvanced_Character' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, K2Node_DynamicCast_bSuccess_1) == 0x000068, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_ComputeDistanceIntoField_ReturnValue) == 0x00006C, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_ComputeDistanceIntoField_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_GreaterEqual_FloatFloat_ReturnValue) == 0x000070, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_GreaterEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_GreaterEqual_FloatFloat_ReturnValue_1) == 0x000071, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_GreaterEqual_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, K2Node_DynamicCast_AsBP_Fire_Sub_Field) == 0x000078, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::K2Node_DynamicCast_AsBP_Fire_Sub_Field' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, K2Node_DynamicCast_bSuccess_2) == 0x000080, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_GetMaster_ReturnValue_1) == 0x000088, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_GetMaster_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x000090, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_ComputeDistanceIntoField_ReturnValue_1) == 0x00009C, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_ComputeDistanceIntoField_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, Temp_int_Loop_Counter_Variable) == 0x0000A0, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_GreaterEqual_FloatFloat_ReturnValue_2) == 0x0000A4, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_GreaterEqual_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_Less_IntInt_ReturnValue) == 0x0000A5, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_Add_IntInt_ReturnValue) == 0x0000A8, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_GetViewTargetCharacter_ReturnValue) == 0x0000B0, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_GetViewTargetCharacter_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_GetPlayerController_ReturnValue) == 0x0000B8, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x0000C0, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, K2Node_DynamicCast_AsBP_Mordhau_Player_Controller) == 0x0000C8, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::K2Node_DynamicCast_AsBP_Mordhau_Player_Controller' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, K2Node_DynamicCast_bSuccess_3) == 0x0000D0, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_IsLocalPlayerController_ReturnValue) == 0x0000D1, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_IsLocalPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_EqualEqual_FloatFloat_ReturnValue) == 0x0000D2, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_EqualEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_BooleanAND_ReturnValue) == 0x0000D3, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_LessEqual_FloatFloat_ReturnValue) == 0x0000D4, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_LessEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_IsValid_ReturnValue) == 0x0000D5, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_Add_FloatFloat_ReturnValue) == 0x0000D8, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_Add_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_GetTimeSeconds_ReturnValue) == 0x0000DC, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_GetTimeSeconds_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField, CallFunc_LessEqual_FloatFloat_ReturnValue_1) == 0x0000E0, "Member 'BP_SmokeField_C_ExecuteUbergraph_BP_SmokeField::CallFunc_LessEqual_FloatFloat_ReturnValue_1' has a wrong offset!");

// Function BP_SmokeField.BP_SmokeField_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_SmokeField_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_SmokeField_C_ReceiveTick) == 0x000004, "Wrong alignment on BP_SmokeField_C_ReceiveTick");
static_assert(sizeof(BP_SmokeField_C_ReceiveTick) == 0x000004, "Wrong size on BP_SmokeField_C_ReceiveTick");
static_assert(offsetof(BP_SmokeField_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'BP_SmokeField_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

}

