#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Shield_RightStabMotion

#include "Basic.hpp"

#include "BP_RightStabMotion_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Shield_RightStabMotion.BP_Shield_RightStabMotion_C
// 0x0000 (0x1118 - 0x1118)
class UBP_Shield_RightStabMotion_C : public UBP_RightStabMotion_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Shield_RightStabMotion_C">();
	}
	static class UBP_Shield_RightStabMotion_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Shield_RightStabMotion_C>();
	}
};
static_assert(alignof(UBP_Shield_RightStabMotion_C) == 0x000008, "Wrong alignment on UBP_Shield_RightStabMotion_C");
static_assert(sizeof(UBP_Shield_RightStabMotion_C) == 0x001118, "Wrong size on UBP_Shield_RightStabMotion_C");

}

