#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_StatEntryBar

#include "Basic.hpp"

#include "BP_StatEntryBar_classes.hpp"
#include "BP_StatEntryBar_parameters.hpp"


namespace SDK
{

// Function BP_StatEntryBar.BP_StatEntryBar_C.ExecuteUbergraph_BP_StatEntryBar
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_StatEntryBar_C::ExecuteUbergraph_BP_StatEntryBar(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatEntryBar_C", "ExecuteUbergraph_BP_StatEntryBar");

	Params::BP_StatEntryBar_C_ExecuteUbergraph_BP_StatEntryBar Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_StatEntryBar.BP_StatEntryBar_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UBP_StatEntryBar_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatEntryBar_C", "PreConstruct");

	Params::BP_StatEntryBar_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_StatEntryBar.BP_StatEntryBar_C.Update
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Percent_0                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_StatEntryBar_C::Update(float Percent_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_StatEntryBar_C", "Update");

	Params::BP_StatEntryBar_C_Update Parms{};

	Parms.Percent_0 = Percent_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

