#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SocialMediaMenu

#include "Basic.hpp"

#include "BP_MenuContentWidget_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_SocialMediaMenu.BP_SocialMediaMenu_C
// 0x0038 (0x02A8 - 0x0270)
class UBP_SocialMediaMenu_C final : public UBP_MenuContentWidget_C
{
public:
	class UBP_SoclalMediaButtonEntry_C*           BP_SoclaiMediaButtonEntry;                         // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_SoclalMediaButtonEntry_C*           BP_SoclalMediaButtonEntry;                         // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_SoclalMediaButtonEntry_C*           BP_SoclalMediaButtonEntry_1;                       // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_SoclalMediaButtonEntry_C*           BP_SoclalMediaButtonEntry_2;                       // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_SoclalMediaButtonEntry_C*           BP_SoclalMediaButtonEntry_3;                       // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBP_SoclalMediaButtonEntry_C*           BP_SoclalMediaButtonEntry_4;                       // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image;                                             // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_SocialMediaMenu_C">();
	}
	static class UBP_SocialMediaMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_SocialMediaMenu_C>();
	}
};
static_assert(alignof(UBP_SocialMediaMenu_C) == 0x000008, "Wrong alignment on UBP_SocialMediaMenu_C");
static_assert(sizeof(UBP_SocialMediaMenu_C) == 0x0002A8, "Wrong size on UBP_SocialMediaMenu_C");
static_assert(offsetof(UBP_SocialMediaMenu_C, BP_SoclaiMediaButtonEntry) == 0x000270, "Member 'UBP_SocialMediaMenu_C::BP_SoclaiMediaButtonEntry' has a wrong offset!");
static_assert(offsetof(UBP_SocialMediaMenu_C, BP_SoclalMediaButtonEntry) == 0x000278, "Member 'UBP_SocialMediaMenu_C::BP_SoclalMediaButtonEntry' has a wrong offset!");
static_assert(offsetof(UBP_SocialMediaMenu_C, BP_SoclalMediaButtonEntry_1) == 0x000280, "Member 'UBP_SocialMediaMenu_C::BP_SoclalMediaButtonEntry_1' has a wrong offset!");
static_assert(offsetof(UBP_SocialMediaMenu_C, BP_SoclalMediaButtonEntry_2) == 0x000288, "Member 'UBP_SocialMediaMenu_C::BP_SoclalMediaButtonEntry_2' has a wrong offset!");
static_assert(offsetof(UBP_SocialMediaMenu_C, BP_SoclalMediaButtonEntry_3) == 0x000290, "Member 'UBP_SocialMediaMenu_C::BP_SoclalMediaButtonEntry_3' has a wrong offset!");
static_assert(offsetof(UBP_SocialMediaMenu_C, BP_SoclalMediaButtonEntry_4) == 0x000298, "Member 'UBP_SocialMediaMenu_C::BP_SoclalMediaButtonEntry_4' has a wrong offset!");
static_assert(offsetof(UBP_SocialMediaMenu_C, Image) == 0x0002A0, "Member 'UBP_SocialMediaMenu_C::Image' has a wrong offset!");

}

