#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ThrowingAxe

#include "Basic.hpp"

#include "BP_ThrowableEquipment_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ThrowingAxe.BP_ThrowingAxe_C
// 0x0000 (0x0D40 - 0x0D40)
class ABP_ThrowingAxe_C : public ABP_ThrowableEquipment_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ThrowingAxe_C">();
	}
	static class ABP_ThrowingAxe_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ThrowingAxe_C>();
	}
};
static_assert(alignof(ABP_ThrowingAxe_C) == 0x000010, "Wrong alignment on ABP_ThrowingAxe_C");
static_assert(sizeof(ABP_ThrowingAxe_C) == 0x000D40, "Wrong size on ABP_ThrowingAxe_C");

}

