#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WoodColor4

#include "Basic.hpp"

#include "Mordhau_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_WoodColor4.BP_WoodColor4_C
// 0x0000 (0x0080 - 0x0080)
class UBP_WoodColor4_C final : public UMordhauColor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_WoodColor4_C">();
	}
	static class UBP_WoodColor4_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_WoodColor4_C>();
	}
};
static_assert(alignof(UBP_WoodColor4_C) == 0x000008, "Wrong alignment on UBP_WoodColor4_C");
static_assert(sizeof(UBP_WoodColor4_C) == 0x000080, "Wrong size on UBP_WoodColor4_C");

}

