#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DemonHordeEnemyArray

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct DemonHordeEnemyArray.DemonHordeEnemyArray
// 0x0050 (0x0050 - 0x0000)
struct FDemonHordeEnemyArray final
{
public:
	TSet<class AMordhauCharacter*>                EnemyCharacters_7_4828AA014C7F76D52D02479FBF356AF0; // 0x0000(0x0050)(Edit, BlueprintVisible, DisableEditOnTemplate)
};
static_assert(alignof(FDemonHordeEnemyArray) == 0x000008, "Wrong alignment on FDemonHordeEnemyArray");
static_assert(sizeof(FDemonHordeEnemyArray) == 0x000050, "Wrong size on FDemonHordeEnemyArray");
static_assert(offsetof(FDemonHordeEnemyArray, EnemyCharacters_7_4828AA014C7F76D52D02479FBF356AF0) == 0x000000, "Member 'FDemonHordeEnemyArray::EnemyCharacters_7_4828AA014C7F76D52D02479FBF356AF0' has a wrong offset!");

}

