#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ImpactShake

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ImpactShake.ImpactShake_C
// 0x0000 (0x0180 - 0x0180)
class UImpactShake_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ImpactShake_C">();
	}
	static class UImpactShake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UImpactShake_C>();
	}
};
static_assert(alignof(UImpactShake_C) == 0x000010, "Wrong alignment on UImpactShake_C");
static_assert(sizeof(UImpactShake_C) == 0x000180, "Wrong size on UImpactShake_C");

}

