#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MainMenu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "MordhauOnlineSubsystem_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass MainMenu.MainMenu_C
// 0x00D0 (0x02F8 - 0x0228)
class AMainMenu_C final : public ALevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0228(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class AActor*                                 CursorActor;                                       // 0x0230(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class ABP_CharacterDoll_C*>            Characters;                                        // 0x0238(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	class UBP_MordhauGameInstance_C*              GameInstance;                                      // 0x0248(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         PartySizeOverride;                                 // 0x0250(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_254[0x4];                                      // 0x0254(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FTransform>                     PawnTransforms;                                    // 0x0258(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<float>                                 FocalDistances;                                    // 0x0268(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          TestingModeEnabled;                                // 0x0278(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_279[0x3];                                      // 0x0279(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         UpdateAllMeshesAtFrame;                            // 0x027C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         RandomPoseInt;                                     // 0x0280(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ShowingHalloween;                                  // 0x0284(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          ShowingChristmas;                                  // 0x0285(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_286[0x2];                                      // 0x0286(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_CharacterDoll_C*                    BP_CharacterDoll_2_ExecuteUbergraph_MainMenu_RefProperty; // 0x0288(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class ABP_CharacterDoll_C*                    BP_CharacterDoll2_ExecuteUbergraph_MainMenu_RefProperty; // 0x0290(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class ABP_CharacterDoll_C*                    BP_CharacterDoll3_ExecuteUbergraph_MainMenu_RefProperty; // 0x0298(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class ABP_RandomProfileDoll_C*                BP_RandomProfileDoll_507_ExecuteUbergraph_MainMenu_RefProperty; // 0x02A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class ABP_MordhauMainMenuPawn_C*              BP_MordhauMainMenuPawn_64_ExecuteUbergraph_MainMenu_RefProperty; // 0x02A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class ABP_CharacterDoll_C*                    BP_CharacterDoll4_ExecuteUbergraph_MainMenu_RefProperty; // 0x02B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class ABP_CharacterDoll_C*                    BP_CharacterDoll5_ExecuteUbergraph_MainMenu_RefProperty; // 0x02B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class ACameraActor*                           TwoPlayers_ExecuteUbergraph_MainMenu_RefProperty;  // 0x02C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class ACameraActor*                           ThreePlayers_ExecuteUbergraph_MainMenu_RefProperty; // 0x02C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class ACameraActor*                           FourPlayers_ExecuteUbergraph_MainMenu_RefProperty; // 0x02D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class ACameraActor*                           FivePlayers_ExecuteUbergraph_MainMenu_RefProperty; // 0x02D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class ACameraActor*                           SixPlayers_ExecuteUbergraph_MainMenu_RefProperty;  // 0x02E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class AActor*                                 Halloween_EdGraph_1_RefProperty;                   // 0x02E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class AActor*                                 Christmas_EdGraph_2_RefProperty;                   // 0x02F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

public:
	void ShowChristmas();
	void ShowHalloween();
	void SetNewsVisibility(bool Visible);
	void ReceiveTick(float DeltaSeconds);
	void OnPartyUpdated(const TArray<struct FPlayFabPlayer>& PartyMembers);
	void AddTestCharacter();
	void ExecuteUbergraph_MainMenu(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MainMenu_C">();
	}
	static class AMainMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMainMenu_C>();
	}
};
static_assert(alignof(AMainMenu_C) == 0x000008, "Wrong alignment on AMainMenu_C");
static_assert(sizeof(AMainMenu_C) == 0x0002F8, "Wrong size on AMainMenu_C");
static_assert(offsetof(AMainMenu_C, UberGraphFrame) == 0x000228, "Member 'AMainMenu_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, CursorActor) == 0x000230, "Member 'AMainMenu_C::CursorActor' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, Characters) == 0x000238, "Member 'AMainMenu_C::Characters' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, GameInstance) == 0x000248, "Member 'AMainMenu_C::GameInstance' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, PartySizeOverride) == 0x000250, "Member 'AMainMenu_C::PartySizeOverride' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, PawnTransforms) == 0x000258, "Member 'AMainMenu_C::PawnTransforms' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, FocalDistances) == 0x000268, "Member 'AMainMenu_C::FocalDistances' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, TestingModeEnabled) == 0x000278, "Member 'AMainMenu_C::TestingModeEnabled' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, UpdateAllMeshesAtFrame) == 0x00027C, "Member 'AMainMenu_C::UpdateAllMeshesAtFrame' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, RandomPoseInt) == 0x000280, "Member 'AMainMenu_C::RandomPoseInt' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, ShowingHalloween) == 0x000284, "Member 'AMainMenu_C::ShowingHalloween' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, ShowingChristmas) == 0x000285, "Member 'AMainMenu_C::ShowingChristmas' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, BP_CharacterDoll_2_ExecuteUbergraph_MainMenu_RefProperty) == 0x000288, "Member 'AMainMenu_C::BP_CharacterDoll_2_ExecuteUbergraph_MainMenu_RefProperty' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, BP_CharacterDoll2_ExecuteUbergraph_MainMenu_RefProperty) == 0x000290, "Member 'AMainMenu_C::BP_CharacterDoll2_ExecuteUbergraph_MainMenu_RefProperty' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, BP_CharacterDoll3_ExecuteUbergraph_MainMenu_RefProperty) == 0x000298, "Member 'AMainMenu_C::BP_CharacterDoll3_ExecuteUbergraph_MainMenu_RefProperty' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, BP_RandomProfileDoll_507_ExecuteUbergraph_MainMenu_RefProperty) == 0x0002A0, "Member 'AMainMenu_C::BP_RandomProfileDoll_507_ExecuteUbergraph_MainMenu_RefProperty' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, BP_MordhauMainMenuPawn_64_ExecuteUbergraph_MainMenu_RefProperty) == 0x0002A8, "Member 'AMainMenu_C::BP_MordhauMainMenuPawn_64_ExecuteUbergraph_MainMenu_RefProperty' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, BP_CharacterDoll4_ExecuteUbergraph_MainMenu_RefProperty) == 0x0002B0, "Member 'AMainMenu_C::BP_CharacterDoll4_ExecuteUbergraph_MainMenu_RefProperty' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, BP_CharacterDoll5_ExecuteUbergraph_MainMenu_RefProperty) == 0x0002B8, "Member 'AMainMenu_C::BP_CharacterDoll5_ExecuteUbergraph_MainMenu_RefProperty' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, TwoPlayers_ExecuteUbergraph_MainMenu_RefProperty) == 0x0002C0, "Member 'AMainMenu_C::TwoPlayers_ExecuteUbergraph_MainMenu_RefProperty' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, ThreePlayers_ExecuteUbergraph_MainMenu_RefProperty) == 0x0002C8, "Member 'AMainMenu_C::ThreePlayers_ExecuteUbergraph_MainMenu_RefProperty' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, FourPlayers_ExecuteUbergraph_MainMenu_RefProperty) == 0x0002D0, "Member 'AMainMenu_C::FourPlayers_ExecuteUbergraph_MainMenu_RefProperty' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, FivePlayers_ExecuteUbergraph_MainMenu_RefProperty) == 0x0002D8, "Member 'AMainMenu_C::FivePlayers_ExecuteUbergraph_MainMenu_RefProperty' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, SixPlayers_ExecuteUbergraph_MainMenu_RefProperty) == 0x0002E0, "Member 'AMainMenu_C::SixPlayers_ExecuteUbergraph_MainMenu_RefProperty' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, Halloween_EdGraph_1_RefProperty) == 0x0002E8, "Member 'AMainMenu_C::Halloween_EdGraph_1_RefProperty' has a wrong offset!");
static_assert(offsetof(AMainMenu_C, Christmas_EdGraph_2_RefProperty) == 0x0002F0, "Member 'AMainMenu_C::Christmas_EdGraph_2_RefProperty' has a wrong offset!");

}

