#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: S_MainMenuNav

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct S_MainMenuNav.S_MainMenuNav
// 0x0020 (0x0020 - 0x0000)
struct FS_MainMenuNav final
{
public:
	class UBP_NavButton_C*                        MainNavTab_4_3022F54544F31998755517B4FF5487B5;     // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UBP_SubNavButton_C*>             SubNavTab_6_52399BE24410CC2E1F99F89A7D8484D1;      // 0x0008(0x0010)(Edit, BlueprintVisible)
	bool                                          Onlyrelevantin_game_11_3BD3347248CA199442141696C699B1D4; // 0x0018(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(FS_MainMenuNav) == 0x000008, "Wrong alignment on FS_MainMenuNav");
static_assert(sizeof(FS_MainMenuNav) == 0x000020, "Wrong size on FS_MainMenuNav");
static_assert(offsetof(FS_MainMenuNav, MainNavTab_4_3022F54544F31998755517B4FF5487B5) == 0x000000, "Member 'FS_MainMenuNav::MainNavTab_4_3022F54544F31998755517B4FF5487B5' has a wrong offset!");
static_assert(offsetof(FS_MainMenuNav, SubNavTab_6_52399BE24410CC2E1F99F89A7D8484D1) == 0x000008, "Member 'FS_MainMenuNav::SubNavTab_6_52399BE24410CC2E1F99F89A7D8484D1' has a wrong offset!");
static_assert(offsetof(FS_MainMenuNav, Onlyrelevantin_game_11_3BD3347248CA199442141696C699B1D4) == 0x000018, "Member 'FS_MainMenuNav::Onlyrelevantin_game_11_3BD3347248CA199442141696C699B1D4' has a wrong offset!");

}

